// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"
	"errors"
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/migrate/entv1/conversion"
	"github.com/neko-sc/ent/entc/integration/migrate/entv1/entity"
	"github.com/neko-sc/ent/schema/field"
)

type ConversionUpdate struct {
	config
	mutation  *ConversionMutation
	err       error
	returning *sqlgraph.Returning

	modifiers []func(*sql.UpdateBuilder)
}

func (b *ConversionUpdate) Set[T any](column ent.ColumnOf[entity.Conversion, T], value T) *ConversionUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *ConversionUpdate) SetOptional[T any](column ent.ColumnOf[entity.Conversion, T], value ent.Option[T]) *ConversionUpdate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *ConversionUpdate) SetExpr[T any](column ent.ColumnOf[entity.Conversion, T], value ent.Expr[T]) *ConversionUpdate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case conversion.FieldName:

	case conversion.FieldInt8ToString:

	case conversion.FieldUint8ToString:

	case conversion.FieldInt16ToString:

	case conversion.FieldUint16ToString:

	case conversion.FieldInt32ToString:

	case conversion.FieldUint32ToString:

	case conversion.FieldInt64ToString:

	case conversion.FieldUint64ToString:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Conversion is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *ConversionUpdate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Conversion, N, K], id K) *ConversionUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *ConversionUpdate) AddIDs[N, K any](edge ent.Relation[entity.Conversion, N, K], ids ...K) *ConversionUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *ConversionUpdate) Mutation() *ConversionMutation { return b.mutation }

func (b *ConversionUpdate) Patch() *ConversionPatch { return b.mutation.patch }
func (b *ConversionUpdate) Apply(p ConversionPatch) *ConversionUpdate {
	b.mutation.patch.apply(p)
	return b
}
func (b *ConversionUpdate) Add[T ent.Number](column ent.ColumnOf[entity.Conversion, T], delta T) *ConversionUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *ConversionUpdate) Append[T any](column ent.ColumnOf[entity.Conversion, T], values T) *ConversionUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *ConversionUpdate) Clear[T any](column ent.ColumnOf[entity.Conversion, T]) *ConversionUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *ConversionUpdate) RemoveIDs[N, K any](edge ent.Relation[entity.Conversion, N, K], ids ...K) *ConversionUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *ConversionUpdate) ClearEdge[N, K any](edge ent.RelationOf[entity.Conversion, N, K]) *ConversionUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *ConversionUpdate) Where(predicates ...ent.Predicate[entity.Conversion]) *ConversionUpdate {
	b.mutation.Where(predicates...)
	return b
}

func (b *ConversionUpdate) Save(ctx context.Context) (int, error) {
	if b.err != nil {
		return 0, b.err
	}
	if err := b.defaults(); err != nil {
		return 0, err
	}
	return b.sqlSave(ctx)
}

func (b *ConversionUpdate) SaveX(ctx context.Context) int {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *ConversionUpdate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *ConversionUpdate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *ConversionUpdate) Returning(ctx context.Context) ([]*Conversion, error) {
	nodes := make([]*Conversion, 0)
	b.returning = &sqlgraph.Returning{Columns: conversion.Columns, Scan: func(rows dialect.Rows) error {
		_node := &Conversion{config: b.config}
		values, err := _node.scanValues(conversion.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(conversion.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Save(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

func (b *ConversionUpdate) defaults() error {

	return nil
}

func (b *ConversionUpdate) check() error {
	if b.err != nil {
		return b.err
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ConversionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ConversionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ConversionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversion.Table, conversion.Columns, sqlgraph.NewFieldSpec(conversion.FieldID, field.TypeInt))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.Name.Get(); ok {
		_spec.SetField(conversion.FieldName, field.TypeString, value)
	}
	if _u.mutation.patch.Name.IsNull() {
		_spec.ClearField(conversion.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.patch.Int8ToString.Get(); ok {
		_spec.SetField(conversion.FieldInt8ToString, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.Int8ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldInt8ToString, field.TypeInt8, value)
	}
	if _u.mutation.patch.Int8ToString.IsNull() {
		_spec.ClearField(conversion.FieldInt8ToString, field.TypeInt8)
	}
	if value, ok := _u.mutation.patch.Uint8ToString.Get(); ok {
		_spec.SetField(conversion.FieldUint8ToString, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.patch.Uint8ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldUint8ToString, field.TypeUint8, value)
	}
	if _u.mutation.patch.Uint8ToString.IsNull() {
		_spec.ClearField(conversion.FieldUint8ToString, field.TypeUint8)
	}
	if value, ok := _u.mutation.patch.Int16ToString.Get(); ok {
		_spec.SetField(conversion.FieldInt16ToString, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.patch.Int16ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldInt16ToString, field.TypeInt16, value)
	}
	if _u.mutation.patch.Int16ToString.IsNull() {
		_spec.ClearField(conversion.FieldInt16ToString, field.TypeInt16)
	}
	if value, ok := _u.mutation.patch.Uint16ToString.Get(); ok {
		_spec.SetField(conversion.FieldUint16ToString, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.patch.Uint16ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldUint16ToString, field.TypeUint16, value)
	}
	if _u.mutation.patch.Uint16ToString.IsNull() {
		_spec.ClearField(conversion.FieldUint16ToString, field.TypeUint16)
	}
	if value, ok := _u.mutation.patch.Int32ToString.Get(); ok {
		_spec.SetField(conversion.FieldInt32ToString, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.patch.Int32ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldInt32ToString, field.TypeInt32, value)
	}
	if _u.mutation.patch.Int32ToString.IsNull() {
		_spec.ClearField(conversion.FieldInt32ToString, field.TypeInt32)
	}
	if value, ok := _u.mutation.patch.Uint32ToString.Get(); ok {
		_spec.SetField(conversion.FieldUint32ToString, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.patch.Uint32ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldUint32ToString, field.TypeUint32, value)
	}
	if _u.mutation.patch.Uint32ToString.IsNull() {
		_spec.ClearField(conversion.FieldUint32ToString, field.TypeUint32)
	}
	if value, ok := _u.mutation.patch.Int64ToString.Get(); ok {
		_spec.SetField(conversion.FieldInt64ToString, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.patch.Int64ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldInt64ToString, field.TypeInt64, value)
	}
	if _u.mutation.patch.Int64ToString.IsNull() {
		_spec.ClearField(conversion.FieldInt64ToString, field.TypeInt64)
	}
	if value, ok := _u.mutation.patch.Uint64ToString.Get(); ok {
		_spec.SetField(conversion.FieldUint64ToString, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.patch.Uint64ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldUint64ToString, field.TypeUint64, value)
	}
	if _u.mutation.patch.Uint64ToString.IsNull() {
		_spec.ClearField(conversion.FieldUint64ToString, field.TypeUint64)
	}
	_spec.Returning = _u.returning
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return _node, nil
}

type ConversionUpdateOne struct {
	config
	mutation *ConversionMutation
	err      error

	fields []string
	old    *Conversion

	modifiers []func(*sql.UpdateBuilder)
}

func (b *ConversionUpdateOne) Set[T any](column ent.ColumnOf[entity.Conversion, T], value T) *ConversionUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *ConversionUpdateOne) SetOptional[T any](column ent.ColumnOf[entity.Conversion, T], value ent.Option[T]) *ConversionUpdateOne {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *ConversionUpdateOne) SetExpr[T any](column ent.ColumnOf[entity.Conversion, T], value ent.Expr[T]) *ConversionUpdateOne {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case conversion.FieldName:

	case conversion.FieldInt8ToString:

	case conversion.FieldUint8ToString:

	case conversion.FieldInt16ToString:

	case conversion.FieldUint16ToString:

	case conversion.FieldInt32ToString:

	case conversion.FieldUint32ToString:

	case conversion.FieldInt64ToString:

	case conversion.FieldUint64ToString:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Conversion is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *ConversionUpdateOne) SetEdge[N, K any](edge ent.UniqueRelation[entity.Conversion, N, K], id K) *ConversionUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *ConversionUpdateOne) AddIDs[N, K any](edge ent.Relation[entity.Conversion, N, K], ids ...K) *ConversionUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *ConversionUpdateOne) Mutation() *ConversionMutation { return b.mutation }

func (b *ConversionUpdateOne) Patch() *ConversionPatch { return b.mutation.patch }
func (b *ConversionUpdateOne) Apply(p ConversionPatch) *ConversionUpdateOne {
	b.mutation.patch.apply(p)
	return b
}
func (b *ConversionUpdateOne) Add[T ent.Number](column ent.ColumnOf[entity.Conversion, T], delta T) *ConversionUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *ConversionUpdateOne) Append[T any](column ent.ColumnOf[entity.Conversion, T], values T) *ConversionUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *ConversionUpdateOne) Clear[T any](column ent.ColumnOf[entity.Conversion, T]) *ConversionUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *ConversionUpdateOne) RemoveIDs[N, K any](edge ent.Relation[entity.Conversion, N, K], ids ...K) *ConversionUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *ConversionUpdateOne) ClearEdge[N, K any](edge ent.RelationOf[entity.Conversion, N, K]) *ConversionUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *ConversionUpdateOne) Where(predicates ...ent.Predicate[entity.Conversion]) *ConversionUpdateOne {
	b.mutation.Where(predicates...)
	return b
}

func (b *ConversionUpdateOne) Save(ctx context.Context) (*Conversion, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *ConversionUpdateOne) SaveX(ctx context.Context) *Conversion {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *ConversionUpdateOne) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *ConversionUpdateOne) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *ConversionUpdateOne) Select(columns ...ent.EntityColumn[entity.Conversion]) *ConversionUpdateOne {
	if len(columns) == 0 {
		panic("ent: Select requires at least one column")
	}
	b.fields = make([]string, len(columns))
	for index, column := range columns {
		b.fields[index] = column.Ref().Name
	}
	return b
}

func (b *ConversionUpdateOne) SaveOld(ctx context.Context) (old *Conversion, updated *Conversion, err error) {
	if !b.driver.Capabilities().ReturningOld {
		return nil, nil, &dialect.UnsupportedError{Feature: "RETURNING OLD", Dialect: dialect.Dialect(b.driver.Dialect())}
	}
	b.old = &Conversion{config: b.config}
	defer func() { b.old = nil }()
	updated, err = b.Save(ctx)
	if err != nil {
		return nil, nil, err
	}
	return b.old, updated, nil
}

func (b *ConversionUpdateOne) defaults() error {

	return nil
}

func (b *ConversionUpdateOne) check() error {
	if b.err != nil {
		return b.err
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ConversionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ConversionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ConversionUpdateOne) sqlSave(ctx context.Context) (_node *Conversion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversion.Table, conversion.Columns, sqlgraph.NewFieldSpec(conversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entv1: missing "Conversion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversion.FieldID)
		for _, f := range fields {
			if !conversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entv1: invalid field %q for query", f)}
			}
			if f != conversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.Name.Get(); ok {
		_spec.SetField(conversion.FieldName, field.TypeString, value)
	}
	if _u.mutation.patch.Name.IsNull() {
		_spec.ClearField(conversion.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.patch.Int8ToString.Get(); ok {
		_spec.SetField(conversion.FieldInt8ToString, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.patch.Int8ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldInt8ToString, field.TypeInt8, value)
	}
	if _u.mutation.patch.Int8ToString.IsNull() {
		_spec.ClearField(conversion.FieldInt8ToString, field.TypeInt8)
	}
	if value, ok := _u.mutation.patch.Uint8ToString.Get(); ok {
		_spec.SetField(conversion.FieldUint8ToString, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.patch.Uint8ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldUint8ToString, field.TypeUint8, value)
	}
	if _u.mutation.patch.Uint8ToString.IsNull() {
		_spec.ClearField(conversion.FieldUint8ToString, field.TypeUint8)
	}
	if value, ok := _u.mutation.patch.Int16ToString.Get(); ok {
		_spec.SetField(conversion.FieldInt16ToString, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.patch.Int16ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldInt16ToString, field.TypeInt16, value)
	}
	if _u.mutation.patch.Int16ToString.IsNull() {
		_spec.ClearField(conversion.FieldInt16ToString, field.TypeInt16)
	}
	if value, ok := _u.mutation.patch.Uint16ToString.Get(); ok {
		_spec.SetField(conversion.FieldUint16ToString, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.patch.Uint16ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldUint16ToString, field.TypeUint16, value)
	}
	if _u.mutation.patch.Uint16ToString.IsNull() {
		_spec.ClearField(conversion.FieldUint16ToString, field.TypeUint16)
	}
	if value, ok := _u.mutation.patch.Int32ToString.Get(); ok {
		_spec.SetField(conversion.FieldInt32ToString, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.patch.Int32ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldInt32ToString, field.TypeInt32, value)
	}
	if _u.mutation.patch.Int32ToString.IsNull() {
		_spec.ClearField(conversion.FieldInt32ToString, field.TypeInt32)
	}
	if value, ok := _u.mutation.patch.Uint32ToString.Get(); ok {
		_spec.SetField(conversion.FieldUint32ToString, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.patch.Uint32ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldUint32ToString, field.TypeUint32, value)
	}
	if _u.mutation.patch.Uint32ToString.IsNull() {
		_spec.ClearField(conversion.FieldUint32ToString, field.TypeUint32)
	}
	if value, ok := _u.mutation.patch.Int64ToString.Get(); ok {
		_spec.SetField(conversion.FieldInt64ToString, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.patch.Int64ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldInt64ToString, field.TypeInt64, value)
	}
	if _u.mutation.patch.Int64ToString.IsNull() {
		_spec.ClearField(conversion.FieldInt64ToString, field.TypeInt64)
	}
	if value, ok := _u.mutation.patch.Uint64ToString.Get(); ok {
		_spec.SetField(conversion.FieldUint64ToString, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.patch.Uint64ToStringAdd.Get(); ok {
		_spec.AddField(conversion.FieldUint64ToString, field.TypeUint64, value)
	}
	if _u.mutation.patch.Uint64ToString.IsNull() {
		_spec.ClearField(conversion.FieldUint64ToString, field.TypeUint64)
	}
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	_node = &Conversion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if _u.old != nil {
		_spec.OldScanValues = _u.old.scanValues
		_spec.OldAssign = _u.old.assignValues
	}
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
