// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"github.com/neko-sc/ent/entc/integration/migrate/entv1/schema"
	"github.com/neko-sc/ent/entc/integration/migrate/entv1/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func(value string) error {
		validators := userDescName.Validators
		if err := validators[0].(func(string) error)(value); err != nil {
			return err
		}
		return nil
	}
	// userDescOldToken is the schema descriptor for old_token field.
	userDescOldToken := userFields[7].Descriptor()
	// user.DefaultOldToken holds the default value on creation for the old_token field.
	user.DefaultOldToken = userDescOldToken.Default.(func() string)
	// userDescBlob is the schema descriptor for blob field.
	userDescBlob := userFields[8].Descriptor()
	// user.BlobValidator is a validator for the "blob" field. It is called by the builders before save.
	user.BlobValidator = func(value []byte) error {
		validators := userDescBlob.Validators
		if err := validators[0].(func([]uint8) error)(value); err != nil {
			return err
		}
		return nil
	}
	// userDescWorkplace is the schema descriptor for workplace field.
	userDescWorkplace := userFields[11].Descriptor()
	// user.WorkplaceValidator is a validator for the "workplace" field. It is called by the builders before save.
	user.WorkplaceValidator = func(value string) error {
		validators := userDescWorkplace.Validators
		if err := validators[0].(func(string) error)(value); err != nil {
			return err
		}
		return nil
	}
}
