// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package license

import (
	time2 "time"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/entc/integration/ent/entity"
)

const (
	// Label holds the string label denoting the license type in the database.
	Label = "license"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// Table holds the table name of the license in the database.
	Table = "licenses"
)

var (
	ID         = ent.OrderedColumn[entity.License, int]{Table: Table, Name: FieldID}
	CreateTime = ent.OrderedColumn[entity.License, time2.Time]{Table: Table, Name: FieldCreateTime}
	UpdateTime = ent.OrderedColumn[entity.License, time2.Time]{Table: Table, Name: FieldUpdateTime}
)

// Alias returns the columns of the licenses table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias: name,
		ID:         ent.OrderedColumn[entity.License, int]{Table: name, Name: FieldID},
		CreateTime: ent.OrderedColumn[entity.License, time2.Time]{Table: name, Name: FieldCreateTime},
		UpdateTime: ent.OrderedColumn[entity.License, time2.Time]{Table: name, Name: FieldUpdateTime},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias string
	ID         ent.OrderedColumn[entity.License, int]
	CreateTime ent.OrderedColumn[entity.License, time2.Time]
	UpdateTime ent.OrderedColumn[entity.License, time2.Time]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.License]) ent.Predicate[entity.License] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.License]) ent.Predicate[entity.License] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.License]) ent.Predicate[entity.License] {
	return ent.Not(predicate)
}

// Columns holds all SQL columns for license fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time2.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time2.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time2.Time
)

// comment from another template.
