// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package info

import (
	"encoding/json"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/edgefield/ent/entity"
)

const (
	// Label holds the string label denoting the info type in the database.
	Label = "info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the info in the database.
	Table = "infos"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "infos"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "id"
)

var (
	ID      = ent.OrderedColumn[entity.Info, int]{Table: Table, Name: FieldID}
	Content = ent.JSONColumn[entity.Info, json.RawMessage]{Table: Table, Name: FieldContent}
	User    = ent.NewUniqueRelation[entity.Info, entity.User, int](EdgeUser, newUserStep)
)

// Alias returns the columns of the infos table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias: name,
		ID:         ent.OrderedColumn[entity.Info, int]{Table: name, Name: FieldID},
		Content:    ent.JSONColumn[entity.Info, json.RawMessage]{Table: name, Name: FieldContent},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias string
	ID         ent.OrderedColumn[entity.Info, int]
	Content    ent.JSONColumn[entity.Info, json.RawMessage]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.Info]) ent.Predicate[entity.Info] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.Info]) ent.Predicate[entity.Info] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.Info]) ent.Predicate[entity.Info] { return ent.Not(predicate) }

// Columns holds all SQL columns for info fields.
var Columns = []string{
	FieldID,
	FieldContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
