// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"slices"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/group"
)

// GroupInsert is the write representation of a Group creation.
type GroupInsert struct {
	Name          ent.Option[string] `json:"name,omitzero"`
	UserIDs       []int              `json:"user_ids,omitzero"`
	TagIDs        []int              `json:"tag_ids,omitzero"`
	JoinedUserIDs []int              `json:"joined_user_ids,omitzero"`
	GroupTagIDs   []int              `json:"group_tag_ids,omitzero"`
	expressions   map[string]func(*sql.Builder)
}

// GroupPatch is the write representation of a Group update.
type GroupPatch struct {
	Name         ent.Option[string]     `json:"name,omitzero"`
	Users        ent.RelationPatch[int] `json:"users,omitzero"`
	Tags         ent.RelationPatch[int] `json:"tags,omitzero"`
	JoinedUsers  ent.RelationPatch[int] `json:"joined_users,omitzero"`
	GroupTags    ent.RelationPatch[int] `json:"group_tags,omitzero"`
	expressions  map[string]func(*sql.Builder)
	clearedEdges map[string]bool
}

func (i *GroupInsert) set(column string, value any) error {
	switch column {

	case group.FieldName:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Group", value, column)}
		}
		i.Name = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Group is not settable", column)}
}

func (i *GroupInsert) setNull(column string) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Group is not nullable", column)}
}

func (i *GroupInsert) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *GroupInsert) setEdge(edge string, id any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Group is not settable", edge)}
}

func (i *GroupInsert) addIDs(edge string, ids ...any) error {
	switch edge {

	case group.EdgeUsers:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Group", id, edge)}
			}
			i.UserIDs = append(i.UserIDs, value)
		}
		return nil

	case group.EdgeTags:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Group", id, edge)}
			}
			i.TagIDs = append(i.TagIDs, value)
		}
		return nil

	case group.EdgeJoinedUsers:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Group", id, edge)}
			}
			i.JoinedUserIDs = append(i.JoinedUserIDs, value)
		}
		return nil

	case group.EdgeGroupTags:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Group", id, edge)}
			}
			i.GroupTagIDs = append(i.GroupTagIDs, value)
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Group does not accept IDs", edge)}
}

func (i *GroupInsert) usersIDs() []int {
	return i.UserIDs
}

func (i *GroupInsert) tagsIDs() []int {
	return i.TagIDs
}

func (i *GroupInsert) joinedusersIDs() []int {
	return i.JoinedUserIDs
}

func (i *GroupInsert) grouptagsIDs() []int {
	return i.GroupTagIDs
}

func (i *GroupPatch) set(column string, value any) error {
	switch column {

	case group.FieldName:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Group", value, column)}
		}
		i.Name = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Group is not settable", column)}
}

func (i *GroupPatch) setNull(column string) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Group is not nullable", column)}
}

func (i *GroupPatch) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *GroupPatch) setEdge(edge string, id any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Group is not settable", edge)}
}

func (i *GroupPatch) addIDs(edge string, ids ...any) error {
	switch edge {

	case group.EdgeUsers:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Group", id, edge)}
			}
			i.Users.Add = append(i.Users.Add, value)
		}
		return nil

	case group.EdgeTags:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Group", id, edge)}
			}
			i.Tags.Add = append(i.Tags.Add, value)
		}
		return nil

	case group.EdgeJoinedUsers:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Group", id, edge)}
			}
			i.JoinedUsers.Add = append(i.JoinedUsers.Add, value)
		}
		return nil

	case group.EdgeGroupTags:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Group", id, edge)}
			}
			i.GroupTags.Add = append(i.GroupTags.Add, value)
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Group does not accept IDs", edge)}
}

func (i *GroupPatch) usersIDs() []int {
	return i.Users.Add

}

func (i *GroupPatch) tagsIDs() []int {
	return i.Tags.Add

}

func (i *GroupPatch) joinedusersIDs() []int {
	return i.JoinedUsers.Add

}

func (i *GroupPatch) grouptagsIDs() []int {
	return i.GroupTags.Add

}

func (p *GroupPatch) add(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Group does not support addition", column)}
}

func (p *GroupPatch) appendValues(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Group does not support append", column)}
}

func (p *GroupPatch) removeIDs(edge string, ids ...any) error {
	switch edge {

	case group.EdgeUsers:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.Users.Remove = append(p.Users.Remove, value)
			p.Users.Add = slices.DeleteFunc(p.Users.Add, func(id int) bool { return id == value })
		}
		return nil

	case group.EdgeTags:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.Tags.Remove = append(p.Tags.Remove, value)
			p.Tags.Add = slices.DeleteFunc(p.Tags.Add, func(id int) bool { return id == value })
		}
		return nil

	case group.EdgeJoinedUsers:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.JoinedUsers.Remove = append(p.JoinedUsers.Remove, value)
			p.JoinedUsers.Add = slices.DeleteFunc(p.JoinedUsers.Add, func(id int) bool { return id == value })
		}
		return nil

	case group.EdgeGroupTags:
		for _, id := range ids {
			value, ok := id.(int)
			if !ok {
				return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q", id, edge)}
			}
			p.GroupTags.Remove = append(p.GroupTags.Remove, value)
			p.GroupTags.Add = slices.DeleteFunc(p.GroupTags.Add, func(id int) bool { return id == value })
		}
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Group does not support removal", edge)}
}

func (p *GroupPatch) clearEdge(edge string) error {
	switch edge {

	case group.EdgeUsers:
		p.Users.Clear = true
		return nil

	case group.EdgeTags:
		p.Tags.Clear = true
		return nil

	case group.EdgeJoinedUsers:
		p.JoinedUsers.Clear = true
		return nil

	case group.EdgeGroupTags:
		p.GroupTags.Clear = true
		return nil

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Group cannot be cleared", edge)}
}

func (p *GroupPatch) apply(other GroupPatch) {

	if other.Name.IsSet() {
		p.Name = other.Name
		delete(p.expressions, group.FieldName)
	}

	p.Users.Add = append(p.Users.Add, other.Users.Add...)
	p.Users.Remove = append(p.Users.Remove, other.Users.Remove...)
	p.Users.Clear = p.Users.Clear || other.Users.Clear

	p.Tags.Add = append(p.Tags.Add, other.Tags.Add...)
	p.Tags.Remove = append(p.Tags.Remove, other.Tags.Remove...)
	p.Tags.Clear = p.Tags.Clear || other.Tags.Clear

	p.JoinedUsers.Add = append(p.JoinedUsers.Add, other.JoinedUsers.Add...)
	p.JoinedUsers.Remove = append(p.JoinedUsers.Remove, other.JoinedUsers.Remove...)
	p.JoinedUsers.Clear = p.JoinedUsers.Clear || other.JoinedUsers.Clear

	p.GroupTags.Add = append(p.GroupTags.Add, other.GroupTags.Add...)
	p.GroupTags.Remove = append(p.GroupTags.Remove, other.GroupTags.Remove...)
	p.GroupTags.Clear = p.GroupTags.Clear || other.GroupTags.Clear

	for column, render := range other.expressions {
		p.setExpr(column, render)
	}
	for edge, clear := range other.clearedEdges {
		if clear {
			if p.clearedEdges == nil {
				p.clearedEdges = make(map[string]bool)
			}
			p.clearedEdges[edge] = true
		}
	}
}
