// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/entity"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/relationship"
)

// RelationshipDelete is the builder for deleting a Relationship entity.
type RelationshipDelete struct {
	config

	mutation  *RelationshipMutation
	returning *sqlgraph.Returning
}

// Where appends a list predicates to the RelationshipDelete builder.
func (_d *RelationshipDelete) Where(predicates ...ent.Predicate[entity.Relationship]) *RelationshipDelete {
	_d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RelationshipDelete) Exec(ctx context.Context) (int, error) {
	return _d.sqlExec(ctx)
}

func (b *RelationshipDelete) Returning(ctx context.Context) ([]*Relationship, error) {
	nodes := make([]*Relationship, 0)
	b.returning = &sqlgraph.Returning{Columns: relationship.Columns, Scan: func(rows dialect.Rows) error {
		_node := &Relationship{config: b.config}
		values, err := _node.scanValues(relationship.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(relationship.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Exec(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RelationshipDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RelationshipDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(relationship.Table, nil)
	if ps := _d.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_spec.Returning = _d.returning
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// RelationshipDeleteOne is the builder for deleting a single Relationship entity.
type RelationshipDeleteOne struct {
	_d *RelationshipDelete
}

// Where appends a list predicates to the RelationshipDelete builder.
func (_d *RelationshipDeleteOne) Where(predicates ...ent.Predicate[entity.Relationship]) *RelationshipDeleteOne {
	_d._d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query.
func (_d *RelationshipDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{relationship.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RelationshipDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
