// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/relationship"
)

// RelationshipInsert is the write representation of a Relationship creation.
type RelationshipInsert struct {
	Weight      ent.Option[int] `json:"weight,omitzero"`
	UserID      int             `json:"user_id"`
	RelativeID  int             `json:"relative_id"`
	InfoID      ent.Option[int] `json:"info_id,omitzero"`
	expressions map[string]func(*sql.Builder)
}

// RelationshipPatch is the write representation of a Relationship update.
type RelationshipPatch struct {
	Weight       ent.Option[int] `json:"weight,omitzero"`
	WeightAdd    ent.Option[int] `json:"weight_add,omitzero"`
	UserID       ent.Option[int] `json:"user_id,omitzero"`
	RelativeID   ent.Option[int] `json:"relative_id,omitzero"`
	InfoID       ent.Option[int] `json:"info_id,omitzero"`
	expressions  map[string]func(*sql.Builder)
	clearedEdges map[string]bool
}

func (i *RelationshipInsert) set(column string, value any) error {
	switch column {

	case relationship.FieldWeight:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Relationship", value, column)}
		}
		i.Weight = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case relationship.FieldUserID:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Relationship", value, column)}
		}
		i.UserID = v

		delete(i.expressions, column)
		return nil

	case relationship.FieldRelativeID:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Relationship", value, column)}
		}
		i.RelativeID = v

		delete(i.expressions, column)
		return nil

	case relationship.FieldInfoID:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Relationship", value, column)}
		}
		i.InfoID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Relationship is not settable", column)}
}

func (i *RelationshipInsert) setNull(column string) error {
	switch column {

	case relationship.FieldInfoID:
		i.InfoID = ent.Null[int]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Relationship is not nullable", column)}
}

func (i *RelationshipInsert) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *RelationshipInsert) setEdge(edge string, id any) error {
	switch edge {

	case relationship.EdgeUser:
		value, ok := id.(int)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Relationship", id, edge)}
		}
		return i.set(relationship.FieldUserID, value)

	case relationship.EdgeRelative:
		value, ok := id.(int)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Relationship", id, edge)}
		}
		return i.set(relationship.FieldRelativeID, value)

	case relationship.EdgeInfo:
		value, ok := id.(int)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Relationship", id, edge)}
		}
		return i.set(relationship.FieldInfoID, value)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Relationship is not settable", edge)}
}

func (i *RelationshipInsert) addIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Relationship does not accept IDs", edge)}
}

func (i *RelationshipInsert) userIDs() []int {

	return []int{i.UserID}

}

func (i *RelationshipInsert) relativeIDs() []int {

	return []int{i.RelativeID}

}

func (i *RelationshipInsert) infoIDs() []int {

	if id, ok := i.InfoID.Get(); ok {
		return []int{id}
	}
	return nil

}

func (i *RelationshipPatch) set(column string, value any) error {
	switch column {

	case relationship.FieldWeight:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Relationship", value, column)}
		}
		i.Weight = ent.Some(v)

		i.WeightAdd = ent.Unset[int]()

		delete(i.expressions, column)
		return nil

	case relationship.FieldUserID:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Relationship", value, column)}
		}
		i.UserID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case relationship.FieldRelativeID:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Relationship", value, column)}
		}
		i.RelativeID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case relationship.FieldInfoID:
		v, ok := value.(int)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Relationship", value, column)}
		}
		i.InfoID = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Relationship is not settable", column)}
}

func (i *RelationshipPatch) setNull(column string) error {
	switch column {

	case relationship.FieldInfoID:
		i.InfoID = ent.Null[int]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Relationship is not nullable", column)}
}

func (i *RelationshipPatch) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *RelationshipPatch) setEdge(edge string, id any) error {
	switch edge {

	case relationship.EdgeUser:
		value, ok := id.(int)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Relationship", id, edge)}
		}
		return i.set(relationship.FieldUserID, value)

	case relationship.EdgeRelative:
		value, ok := id.(int)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Relationship", id, edge)}
		}
		return i.set(relationship.FieldRelativeID, value)

	case relationship.EdgeInfo:
		value, ok := id.(int)
		if !ok {
			return &ValidationError{Name: edge, err: fmt.Errorf("ent: unexpected ID type %T for edge %q of Relationship", id, edge)}
		}
		return i.set(relationship.FieldInfoID, value)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Relationship is not settable", edge)}
}

func (i *RelationshipPatch) addIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Relationship does not accept IDs", edge)}
}

func (i *RelationshipPatch) userIDs() []int {

	if id, ok := i.UserID.Get(); ok {
		return []int{id}
	}
	return nil

}

func (i *RelationshipPatch) relativeIDs() []int {

	if id, ok := i.RelativeID.Get(); ok {
		return []int{id}
	}
	return nil

}

func (i *RelationshipPatch) infoIDs() []int {

	if id, ok := i.InfoID.Get(); ok {
		return []int{id}
	}
	return nil

}

func (p *RelationshipPatch) add(column string, value any) error {
	switch column {

	case relationship.FieldWeight:
		delta, ok := value.(int)

		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected addition type %T for field %q", value, column)}
		}
		if current, exists := p.WeightAdd.Get(); exists {
			delta += current
		}
		p.WeightAdd = ent.Some(delta)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Relationship does not support addition", column)}
}

func (p *RelationshipPatch) appendValues(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Relationship does not support append", column)}
}

func (p *RelationshipPatch) removeIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Relationship does not support removal", edge)}
}

func (p *RelationshipPatch) clearEdge(edge string) error {
	switch edge {

	case relationship.EdgeUser:

		return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Relationship is required", edge)}

	case relationship.EdgeRelative:

		return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Relationship is required", edge)}

	case relationship.EdgeInfo:

		if p.clearedEdges == nil {
			p.clearedEdges = make(map[string]bool)
		}
		p.clearedEdges[edge] = true
		return p.setNull(relationship.FieldInfoID)

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Relationship cannot be cleared", edge)}
}

func (p *RelationshipPatch) apply(other RelationshipPatch) {

	if other.Weight.IsSet() {
		p.Weight = other.Weight
		delete(p.expressions, relationship.FieldWeight)
	}

	if value, ok := other.WeightAdd.Get(); ok {
		if current, exists := p.WeightAdd.Get(); exists {
			value += current
		}
		p.WeightAdd = ent.Some(value)
	}

	if other.UserID.IsSet() {
		p.UserID = other.UserID
		delete(p.expressions, relationship.FieldUserID)
	}

	if other.RelativeID.IsSet() {
		p.RelativeID = other.RelativeID
		delete(p.expressions, relationship.FieldRelativeID)
	}

	if other.InfoID.IsSet() {
		p.InfoID = other.InfoID
		delete(p.expressions, relationship.FieldInfoID)
	}

	for column, render := range other.expressions {
		p.setExpr(column, render)
	}
	for edge, clear := range other.clearedEdges {
		if clear {
			if p.clearedEdges == nil {
				p.clearedEdges = make(map[string]bool)
			}
			p.clearedEdges[edge] = true
		}
	}
}
