// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	time2 "time"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/entity"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/group"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/user"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/usergroup"
)

// UserGroup is the model entity for the UserGroup schema.
type UserGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time2.Time `json:"joined_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int `json:"group_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserGroupQuery when eager-loading is set.
	Edges UserGroupEdges `json:"edges"`
}

// UserGroupEdges holds the relations/edges for other nodes in the graph.
type UserGroupEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	counts      map[string]int
}

func (e UserGroupEdges) Loaded[N, K any](edge ent.RelationOf[entity.UserGroup, N, K]) bool {
	switch edge.Ref().Name {
	case "user":
		return e.loadedTypes[0]
	case "group":
		return e.loadedTypes[1]

	default:
		return false
	}
}

func (e *UserGroupEdges) SetLoaded[N, K any](edge ent.RelationOf[entity.UserGroup, N, K], loaded bool) {
	switch edge.Ref().Name {
	case "user":
		e.loadedTypes[0] = loaded
	case "group":
		e.loadedTypes[1] = loaded

	}
}

func (e UserGroupEdges) Count[N, K any](edge ent.Relation[entity.UserGroup, N, K]) (int, bool) {
	count, loaded := e.counts[edge.Ref().Name]
	return count, loaded
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserGroupEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserGroupEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usergroup.FieldID, usergroup.FieldUserID, usergroup.FieldGroupID:
			values[i] = new(*int)
		case usergroup.FieldJoinedAt:
			values[i] = new(*time2.Time)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserGroup fields.
func (_m *UserGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usergroup.FieldID:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil && *value != nil {
				_m.ID = **value
			}
		case usergroup.FieldJoinedAt:

			if value, ok := values[i].(**time2.Time); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value != nil && *value != nil {
				_m.JoinedAt = **value
			}
		case usergroup.FieldUserID:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil && *value != nil {
				_m.UserID = **value
			}
		case usergroup.FieldGroupID:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value != nil && *value != nil {
				_m.GroupID = **value
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the UserGroup entity.
func (_m *UserGroup) QueryUser() *UserQuery {
	return NewUserGroupClient(_m.config).QueryUser(_m)
}

// QueryGroup queries the "group" edge of the UserGroup entity.
func (_m *UserGroup) QueryGroup() *GroupQuery {
	return NewUserGroupClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this UserGroup.
// Note that you need to call UserGroup.Unwrap() before calling this method if this UserGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserGroup) Update() *UserGroupUpdateOne {
	return NewUserGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserGroup) Unwrap() *UserGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserGroup) String() string {
	var builder strings.Builder
	builder.WriteString("UserGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteByte(')')
	return builder.String()
}

// UserGroups is a parsable slice of UserGroup.
type UserGroups []*UserGroup
