// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/entity"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/usergroup"
	"github.com/neko-sc/ent/schema/field"
)

// UserGroupDelete is the builder for deleting a UserGroup entity.
type UserGroupDelete struct {
	config

	mutation  *UserGroupMutation
	returning *sqlgraph.Returning
}

// Where appends a list predicates to the UserGroupDelete builder.
func (_d *UserGroupDelete) Where(predicates ...ent.Predicate[entity.UserGroup]) *UserGroupDelete {
	_d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserGroupDelete) Exec(ctx context.Context) (int, error) {
	return _d.sqlExec(ctx)
}

func (b *UserGroupDelete) Returning(ctx context.Context) ([]*UserGroup, error) {
	nodes := make([]*UserGroup, 0)
	b.returning = &sqlgraph.Returning{Columns: usergroup.Columns, Scan: func(rows dialect.Rows) error {
		_node := &UserGroup{config: b.config}
		values, err := _node.scanValues(usergroup.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(usergroup.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Exec(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserGroupDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usergroup.Table, sqlgraph.NewFieldSpec(usergroup.FieldID, field.TypeInt))
	if ps := _d.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_spec.Returning = _d.returning
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// UserGroupDeleteOne is the builder for deleting a single UserGroup entity.
type UserGroupDeleteOne struct {
	_d *UserGroupDelete
}

// Where appends a list predicates to the UserGroupDelete builder.
func (_d *UserGroupDeleteOne) Where(predicates ...ent.Predicate[entity.UserGroup]) *UserGroupDeleteOne {
	_d._d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usergroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserGroupDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
