// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package relationshipinfo

import (
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/entity"
)

const (
	// Label holds the string label denoting the relationshipinfo type in the database.
	Label = "relationship_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// Table holds the table name of the relationshipinfo in the database.
	Table = "relationship_infos"
)

var (
	ID   = ent.OrderedColumn[entity.RelationshipInfo, int]{Table: Table, Name: FieldID}
	Text = ent.StringColumn[entity.RelationshipInfo, string]{Table: Table, Name: FieldText}
)

// Alias returns the columns of the relationship_infos table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias: name,
		ID:         ent.OrderedColumn[entity.RelationshipInfo, int]{Table: name, Name: FieldID},
		Text:       ent.StringColumn[entity.RelationshipInfo, string]{Table: name, Name: FieldText},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias string
	ID         ent.OrderedColumn[entity.RelationshipInfo, int]
	Text       ent.StringColumn[entity.RelationshipInfo, string]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.RelationshipInfo]) ent.Predicate[entity.RelationshipInfo] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.RelationshipInfo]) ent.Predicate[entity.RelationshipInfo] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.RelationshipInfo]) ent.Predicate[entity.RelationshipInfo] {
	return ent.Not(predicate)
}

// Columns holds all SQL columns for relationshipinfo fields.
var Columns = []string{
	FieldID,
	FieldText,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
