// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package pet

import (
	time2 "time"

	"github.com/google/uuid"
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/ent/entity"
)

const (
	// Label holds the string label denoting the pet type in the database.
	Label = "pet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldTrained holds the string denoting the trained field in the database.
	FieldTrained = "trained"
	// FieldOptionalTime holds the string denoting the optional_time field in the database.
	FieldOptionalTime = "optional_time"
	// EdgeTeam holds the string denoting the team edge name in mutations.
	EdgeTeam = "team"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the pet in the database.
	Table = "pet"
	// TeamTable is the table that holds the team relation/edge.
	TeamTable = "pet"
	// TeamInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	TeamInverseTable = "users"
	// TeamColumn is the table column denoting the team relation/edge.
	TeamColumn = "user_team"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "pet"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_pets"
)

var (
	ID           = ent.OrderedColumn[entity.Pet, int]{Table: Table, Name: FieldID}
	Age          = ent.OrderedColumn[entity.Pet, float64]{Table: Table, Name: FieldAge}
	Name         = ent.StringColumn[entity.Pet, string]{Table: Table, Name: FieldName}
	UUID         = ent.OrderedColumn[entity.Pet, uuid.UUID]{Table: Table, Name: FieldUUID}
	Nickname     = ent.StringColumn[entity.Pet, string]{Table: Table, Name: FieldNickname}
	Trained      = ent.Column[entity.Pet, bool]{Table: Table, Name: FieldTrained}
	OptionalTime = ent.OrderedColumn[entity.Pet, time2.Time]{Table: Table, Name: FieldOptionalTime}
	Team         = ent.NewUniqueRelation[entity.Pet, entity.User, int](EdgeTeam, newTeamStep)
	Owner        = ent.NewUniqueRelation[entity.Pet, entity.User, int](EdgeOwner, newOwnerStep)
)

// Alias returns the columns of the pet table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias:   name,
		ID:           ent.OrderedColumn[entity.Pet, int]{Table: name, Name: FieldID},
		Age:          ent.OrderedColumn[entity.Pet, float64]{Table: name, Name: FieldAge},
		Name:         ent.StringColumn[entity.Pet, string]{Table: name, Name: FieldName},
		UUID:         ent.OrderedColumn[entity.Pet, uuid.UUID]{Table: name, Name: FieldUUID},
		Nickname:     ent.StringColumn[entity.Pet, string]{Table: name, Name: FieldNickname},
		Trained:      ent.Column[entity.Pet, bool]{Table: name, Name: FieldTrained},
		OptionalTime: ent.OrderedColumn[entity.Pet, time2.Time]{Table: name, Name: FieldOptionalTime},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias   string
	ID           ent.OrderedColumn[entity.Pet, int]
	Age          ent.OrderedColumn[entity.Pet, float64]
	Name         ent.StringColumn[entity.Pet, string]
	UUID         ent.OrderedColumn[entity.Pet, uuid.UUID]
	Nickname     ent.StringColumn[entity.Pet, string]
	Trained      ent.Column[entity.Pet, bool]
	OptionalTime ent.OrderedColumn[entity.Pet, time2.Time]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.Pet]) ent.Predicate[entity.Pet] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.Pet]) ent.Predicate[entity.Pet] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.Pet]) ent.Predicate[entity.Pet] { return ent.Not(predicate) }

// Columns holds all SQL columns for pet fields.
var Columns = []string{
	FieldID,
	FieldAge,
	FieldName,
	FieldUUID,
	FieldNickname,
	FieldTrained,
	FieldOptionalTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "pet"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_pets",
	"user_team",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAge holds the default value on creation for the "age" field.
	DefaultAge float64
	// DefaultTrained holds the default value on creation for the "trained" field.
	DefaultTrained bool
)

func newTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, TeamTable, TeamColumn),
	)
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}

// comment from another template.
