// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package group

import (
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/entc/integration/template/ent/entity"
)

const (
	// Label holds the string label denoting the group type in the database.
	Label = "group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMaxUsers holds the string denoting the max_users field in the database.
	FieldMaxUsers = "max_users"
	// Table holds the table name of the group in the database.
	Table = "groups"
)

var (
	ID       = ent.OrderedColumn[entity.Group, int]{Table: Table, Name: FieldID}
	MaxUsers = ent.OrderedColumn[entity.Group, int]{Table: Table, Name: FieldMaxUsers}
)

// Alias returns the columns of the groups table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias: name,
		ID:         ent.OrderedColumn[entity.Group, int]{Table: name, Name: FieldID},
		MaxUsers:   ent.OrderedColumn[entity.Group, int]{Table: name, Name: FieldMaxUsers},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias string
	ID         ent.OrderedColumn[entity.Group, int]
	MaxUsers   ent.OrderedColumn[entity.Group, int]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.Group]) ent.Predicate[entity.Group] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.Group]) ent.Predicate[entity.Group] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.Group]) ent.Predicate[entity.Group] {
	return ent.Not(predicate)
}

// Columns holds all SQL columns for group fields.
var Columns = []string{
	FieldID,
	FieldMaxUsers,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
