// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/ent/card"
	"github.com/neko-sc/ent/entc/integration/ent/entity"
	"github.com/neko-sc/ent/entc/integration/ent/spec"
	"github.com/neko-sc/ent/entc/integration/ent/user"
	"github.com/neko-sc/ent/schema/field"
)

type CardCreate struct {
	config
	mutation    *CardMutation
	err         error
	fromBuilder bool
	present     map[string]struct{}

	conflict []sql.ConflictOption
}

func (b *CardCreate) Set[T any](column ent.ColumnOf[entity.Card, T], value T) *CardCreate {
	if b.err == nil {
		b.err = b.mutation.insert.set(column.Ref().Name, value)
	}
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b
}
func (b *CardCreate) SetOptional[T any](column ent.ColumnOf[entity.Card, T], value ent.Option[T]) *CardCreate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.insert.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *CardCreate) SetExpr[T any](column ent.ColumnOf[entity.Card, T], value ent.Expr[T]) *CardCreate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case card.FieldCreateTime:

	case card.FieldUpdateTime:

	case card.FieldBalance:

	case card.FieldNumber:

	case card.FieldName:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Card is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.insert.setExpr(column.Ref().Name, value.Render)
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b

}
func (b *CardCreate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Card, N, K], id K) *CardCreate {
	if b.err == nil {
		b.err = b.mutation.insert.setEdge(edge.Ref().Name, id)
	}

	switch edge.Ref().Name {

	}

	return b
}
func (b *CardCreate) AddIDs[N, K any](edge ent.Relation[entity.Card, N, K], ids ...K) *CardCreate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.insert.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CardCreate) Mutation() *CardMutation { return b.mutation }

func (b *CardCreate) Insert() *CardInsert { return b.mutation.insert }

func (b *CardCreate) Save(ctx context.Context) (*Card, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *CardCreate) SaveX(ctx context.Context) *Card {
	node, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

func (b *CardCreate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CardCreate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *CardCreate) defaults() error {

	if b.mutation.insert.CreateTime.IsUnset() && b.mutation.insert.expressions[card.FieldCreateTime] == nil {
		if card.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized card.DefaultCreateTime")
		}
		b.mutation.insert.CreateTime = ent.Some(card.DefaultCreateTime())
	}

	if b.mutation.insert.UpdateTime.IsUnset() && b.mutation.insert.expressions[card.FieldUpdateTime] == nil {
		if card.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized card.DefaultUpdateTime")
		}
		b.mutation.insert.UpdateTime = ent.Some(card.DefaultUpdateTime())
	}

	if b.mutation.insert.Balance.IsUnset() && b.mutation.insert.expressions[card.FieldBalance] == nil {

		b.mutation.insert.Balance = ent.Some(card.DefaultBalance)
	}

	return nil
}

func (b *CardCreate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.insert.CreateTime.IsNull() {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: field "Card.create_time" is not nullable`)}
	}

	if b.mutation.insert.UpdateTime.IsNull() {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: field "Card.update_time" is not nullable`)}
	}

	if b.mutation.insert.Balance.IsNull() {
		return &ValidationError{Name: "balance", err: errors.New(`ent: field "Card.balance" is not nullable`)}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[card.FieldNumber]; b.fromBuilder && !present {
			return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "Card.number"`)}
		}
	}

	if b.mutation.insert.expressions[card.FieldNumber] == nil {
		v := b.mutation.insert.Number

		if err := card.NumberValidator(v); err != nil {
			return &ValidationError{Name: "number", err: fmt.Errorf(`ent: validator failed for field "Card.number": %w`, err)}
		}

	}

	if b.mutation.insert.expressions[card.FieldName] == nil {
		if v, ok := b.mutation.insert.Name.Get(); ok {

			if err := card.NameValidator(v); err != nil {
				return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Card.name": %w`, err)}
			}

		}
	}

	return nil
}

func (_c *CardCreate) sqlSave(ctx context.Context) (*Card, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	node, spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	_c.mutation.id = &node.ID
	return node, nil
}

func (_c *CardCreate) createSpec() (*Card, *sqlgraph.CreateSpec, error) {
	_node := &Card{config: _c.config}
	_spec := sqlgraph.NewCreateSpec(card.Table, sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt))

	_spec.OnConflict = _c.conflict

	if value, ok := _c.mutation.insert.CreateTime.Get(); ok {
		_spec.SetField(card.FieldCreateTime, field.TypeTime, value)
	}
	if _c.mutation.insert.CreateTime.IsNull() {
		_spec.SetField(card.FieldCreateTime, field.TypeTime, nil)
	}

	if value, ok := _c.mutation.insert.UpdateTime.Get(); ok {
		_spec.SetField(card.FieldUpdateTime, field.TypeTime, value)
	}
	if _c.mutation.insert.UpdateTime.IsNull() {
		_spec.SetField(card.FieldUpdateTime, field.TypeTime, nil)
	}

	if value, ok := _c.mutation.insert.Balance.Get(); ok {
		_spec.SetField(card.FieldBalance, field.TypeFloat64, value)
	}
	if _c.mutation.insert.Balance.IsNull() {
		_spec.SetField(card.FieldBalance, field.TypeFloat64, nil)
	}

	if _, present := _c.present[card.FieldNumber]; !_c.fromBuilder || present {
		value := _c.mutation.insert.Number
		_spec.SetField(card.FieldNumber, field.TypeString, value)
	}

	if value, ok := _c.mutation.insert.Name.Get(); ok {
		_spec.SetField(card.FieldName, field.TypeString, value)
	}
	if _c.mutation.insert.Name.IsNull() {
		_spec.SetField(card.FieldName, field.TypeString, nil)
	}

	_spec.Expressions = _c.mutation.insert.expressions

	if nodes := _c.mutation.insert.ownerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   card.OwnerTable,
			Columns: []string{card.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	if nodes := _c.mutation.insert.specIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   card.SpecTable,
			Columns: card.SpecPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spec.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	_spec.Returning = &sqlgraph.Returning{Columns: card.Columns, Scan: func(rows dialect.Rows) error {
		values, err := _node.scanValues(card.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(card.Columns, values); err != nil {
			return err
		}

		_spec.ID.Value = _node.ID

		return nil
	}}
	return _node, _spec, nil
}

type CardUpsertOne struct{ create *CardCreate }

func (b *CardCreate) OnConflict(columns ...ent.EntityColumn[entity.Card]) *CardUpsertOne {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *CardCreate) OnConflictConstraint(name string) *CardUpsertOne {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *CardCreate) OnConflictOptions(options ...sql.ConflictOption) *CardUpsertOne {
	b.conflict = options
	return &CardUpsertOne{create: b}
}

func (u *CardUpsertOne) DoNothing() *CardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *CardUpsertOne) DoSelect() *CardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *CardUpsertOne) Ignore() *CardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *CardUpsertOne) DoUpdate(set func(*CardUpsert)) *CardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&CardUpsert{UpdateSet: update}) }))
	return u
}

func (u *CardUpsertOne) UpdateNewValues() *CardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case card.FieldID:
				update.SetIgnore(column)

			case card.FieldCreateTime:
				update.SetIgnore(column)

			case card.FieldNumber:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *CardUpsertOne) Where(predicates ...ent.Predicate[entity.Card]) *CardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(card.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CardUpsertOne) UpdateWhere(predicates ...ent.Predicate[entity.Card]) *CardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(card.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CardUpsertOne) Save(ctx context.Context) (*Card, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for CardCreate.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *CardUpsertOne) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *CardUpsertOne) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (u *CardUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

func (u *CardUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

type CardUpsert struct{ *sql.UpdateSet }

func (u *CardUpsert) Set[T any](column ent.ColumnOf[entity.Card, T], value T) *CardUpsert {
	switch column.Ref().Name {

	case card.FieldUpdateTime:
		u.UpdateSet.Set(column.Ref().Name, value)

	case card.FieldBalance:
		u.UpdateSet.Set(column.Ref().Name, value)

	case card.FieldName:
		u.UpdateSet.Set(column.Ref().Name, value)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Card is not settable", column.Ref().Name)})
	}
	return u
}

func (u *CardUpsert) SetExpr[T any](column ent.ColumnOf[entity.Card, T], value ent.Expr[T]) *CardUpsert {
	switch column.Ref().Name {

	case card.FieldUpdateTime:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case card.FieldBalance:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case card.FieldName:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Card is not settable", column.Ref().Name)})
	}
	return u
}

func (u *CardUpsert) UpdateNewValue[T any](column ent.ColumnOf[entity.Card, T]) *CardUpsert {
	switch column.Ref().Name {

	case card.FieldUpdateTime:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case card.FieldBalance:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case card.FieldName:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Card is not settable", column.Ref().Name)})
	}
	return u
}

func (u *CardUpsert) Add[T ent.Number](column ent.ColumnOf[entity.Card, T], delta T) *CardUpsert {
	switch column.Ref().Name {

	case card.FieldBalance:
		u.UpdateSet.Add(column.Ref().Name, delta)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Card does not support addition", column.Ref().Name)})
	}
	return u
}

func (u *CardUpsert) Clear[T any](column ent.ColumnOf[entity.Card, T]) *CardUpsert {
	switch column.Ref().Name {

	case card.FieldName:
		u.UpdateSet.SetNull(column.Ref().Name)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Card is not nullable", column.Ref().Name)})
	}
	return u
}

type CardCreateBulk struct {
	config
	err      error
	builders []*CardCreate

	conflict []sql.ConflictOption
}

func (_c *CardCreateBulk) Save(ctx context.Context) ([]*Card, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	nodes := make([]*Card, len(_c.builders))
	specs := make([]*sqlgraph.CreateSpec, len(nodes))
	for index, builder := range _c.builders {
		if builder.err != nil {
			return nil, builder.err
		}
		if err := builder.defaults(); err != nil {
			return nil, err
		}
		if err := builder.check(); err != nil {
			return nil, err
		}
		var err error
		nodes[index], specs[index], err = builder.createSpec()
		if err != nil {
			return nil, err
		}
	}
	if len(specs) == 0 {
		return nodes, nil
	}
	spec := &sqlgraph.BatchCreateSpec{Nodes: specs}

	spec.OnConflict = _c.conflict

	if err := sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	result := nodes[:0]
	for index, builder := range _c.builders {
		if specs[index].Skipped {
			continue
		}
		builder.mutation.id = &nodes[index].ID
		result = append(result, nodes[index])
	}
	return result, nil
}

func (b *CardCreateBulk) SaveX(ctx context.Context) []*Card {
	nodes, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

func (b *CardCreateBulk) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CardCreateBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

type CardUpsertBulk struct{ create *CardCreateBulk }

func (b *CardCreateBulk) OnConflict(columns ...ent.EntityColumn[entity.Card]) *CardUpsertBulk {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *CardCreateBulk) OnConflictConstraint(name string) *CardUpsertBulk {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *CardCreateBulk) OnConflictOptions(options ...sql.ConflictOption) *CardUpsertBulk {
	b.conflict = options
	return &CardUpsertBulk{create: b}
}

func (u *CardUpsertBulk) DoNothing() *CardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *CardUpsertBulk) DoSelect() *CardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *CardUpsertBulk) Ignore() *CardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *CardUpsertBulk) DoUpdate(set func(*CardUpsert)) *CardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&CardUpsert{UpdateSet: update}) }))
	return u
}

func (u *CardUpsertBulk) UpdateNewValues() *CardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case card.FieldID:
				update.SetIgnore(column)

			case card.FieldCreateTime:
				update.SetIgnore(column)

			case card.FieldNumber:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *CardUpsertBulk) Where(predicates ...ent.Predicate[entity.Card]) *CardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(card.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CardUpsertBulk) UpdateWhere(predicates ...ent.Predicate[entity.Card]) *CardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(card.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CardUpsertBulk) Save(ctx context.Context) ([]*Card, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for CardCreateBulk.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *CardUpsertBulk) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *CardUpsertBulk) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}
