// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package entity

// Friendship is the phantom type sealing Friendship columns, edges and predicates.
type Friendship struct{}

// Group is the phantom type sealing Group columns, edges and predicates.
type Group struct{}

// Pet is the phantom type sealing Pet columns, edges and predicates.
type Pet struct{}

// User is the phantom type sealing User columns, edges and predicates.
type User struct{}
