// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"

	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/examples/compositetypes/ent/predicate"
	"github.com/neko-sc/ent/examples/compositetypes/ent/schema"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v *schema.Address) predicate.User {
	vc, err := ValueScanner.Address.Value(v)
	return predicate.UserOrErr(sql.FieldEQ(FieldAddress, vc), err)
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v *schema.Address) predicate.User {
	vc, err := ValueScanner.Address.Value(v)
	return predicate.UserOrErr(sql.FieldEQ(FieldAddress, vc), err)
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v *schema.Address) predicate.User {
	vc, err := ValueScanner.Address.Value(v)
	return predicate.UserOrErr(sql.FieldNEQ(FieldAddress, vc), err)
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...*schema.Address) predicate.User {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Address.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.UserOrErr(sql.FieldIn(FieldAddress, v...), err)
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...*schema.Address) predicate.User {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Address.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.UserOrErr(sql.FieldNotIn(FieldAddress, v...), err)
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v *schema.Address) predicate.User {
	vc, err := ValueScanner.Address.Value(v)
	return predicate.UserOrErr(sql.FieldGT(FieldAddress, vc), err)
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v *schema.Address) predicate.User {
	vc, err := ValueScanner.Address.Value(v)
	return predicate.UserOrErr(sql.FieldGTE(FieldAddress, vc), err)
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v *schema.Address) predicate.User {
	vc, err := ValueScanner.Address.Value(v)
	return predicate.UserOrErr(sql.FieldLT(FieldAddress, vc), err)
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v *schema.Address) predicate.User {
	vc, err := ValueScanner.Address.Value(v)
	return predicate.UserOrErr(sql.FieldLTE(FieldAddress, vc), err)
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v *schema.Address) predicate.User {
	vc, err := ValueScanner.Address.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("address value is not a string: %T", vc)
	}
	return predicate.UserOrErr(sql.FieldContains(FieldAddress, vcs), err)
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v *schema.Address) predicate.User {
	vc, err := ValueScanner.Address.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("address value is not a string: %T", vc)
	}
	return predicate.UserOrErr(sql.FieldHasPrefix(FieldAddress, vcs), err)
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v *schema.Address) predicate.User {
	vc, err := ValueScanner.Address.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("address value is not a string: %T", vc)
	}
	return predicate.UserOrErr(sql.FieldHasSuffix(FieldAddress, vcs), err)
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
