// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/customid/ent/entity"
	"github.com/neko-sc/ent/entc/integration/customid/ent/link"
	uuidc "github.com/neko-sc/ent/entc/integration/customid/uuidcompatible"
	"github.com/neko-sc/ent/schema/field"
)

type LinkCreate struct {
	config
	mutation    *LinkMutation
	err         error
	fromBuilder bool
	present     map[string]struct{}

	conflict []sql.ConflictOption
}

func (b *LinkCreate) Set[T any](column ent.ColumnOf[entity.Link, T], value T) *LinkCreate {
	if b.err == nil {
		b.err = b.mutation.insert.set(column.Ref().Name, value)
	}
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b
}
func (b *LinkCreate) SetOptional[T any](column ent.ColumnOf[entity.Link, T], value ent.Option[T]) *LinkCreate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.insert.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *LinkCreate) SetExpr[T any](column ent.ColumnOf[entity.Link, T], value ent.Expr[T]) *LinkCreate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case link.FieldID:

	case link.FieldLinkInformation:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Link is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.insert.setExpr(column.Ref().Name, value.Render)
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b

}
func (b *LinkCreate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Link, N, K], id K) *LinkCreate {
	if b.err == nil {
		b.err = b.mutation.insert.setEdge(edge.Ref().Name, id)
	}

	switch edge.Ref().Name {

	}

	return b
}
func (b *LinkCreate) AddIDs[N, K any](edge ent.Relation[entity.Link, N, K], ids ...K) *LinkCreate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.insert.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *LinkCreate) Mutation() *LinkMutation { return b.mutation }

func (b *LinkCreate) Insert() *LinkInsert { return b.mutation.insert }

func (b *LinkCreate) Save(ctx context.Context) (*Link, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *LinkCreate) SaveX(ctx context.Context) *Link {
	node, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

func (b *LinkCreate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *LinkCreate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *LinkCreate) defaults() error {

	if b.mutation.insert.ID.IsUnset() && b.mutation.insert.expressions[link.FieldID] == nil {
		if link.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized link.DefaultID")
		}
		b.mutation.insert.ID = ent.Some(link.DefaultID())
	}

	if b.mutation.insert.LinkInformation.IsUnset() && b.mutation.insert.expressions[link.FieldLinkInformation] == nil {

		b.mutation.insert.LinkInformation = ent.Some(link.DefaultLinkInformation)
	}

	return nil
}

func (b *LinkCreate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.insert.ID.IsNull() {
		return &ValidationError{Name: "id", err: errors.New(`ent: field "Link.id" is not nullable`)}
	}

	if b.mutation.insert.LinkInformation.IsNull() {
		return &ValidationError{Name: "link_information", err: errors.New(`ent: field "Link.link_information" is not nullable`)}
	}

	return nil
}

func (_c *LinkCreate) sqlSave(ctx context.Context) (*Link, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	node, spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	_c.mutation.id = &node.ID
	return node, nil
}

func (_c *LinkCreate) createSpec() (*Link, *sqlgraph.CreateSpec, error) {
	_node := &Link{config: _c.config}
	_spec := sqlgraph.NewCreateSpec(link.Table, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUUID))

	_spec.OnConflict = _c.conflict

	if value, ok := _c.mutation.insert.ID.Get(); ok {
		_spec.ID.Value = &value
	}

	if value, ok := _c.mutation.insert.LinkInformation.Get(); ok {
		_spec.SetField(link.FieldLinkInformation, field.TypeJSON, value)
	}
	if _c.mutation.insert.LinkInformation.IsNull() {
		_spec.SetField(link.FieldLinkInformation, field.TypeJSON, nil)
	}

	_spec.Expressions = _c.mutation.insert.expressions

	_spec.Returning = &sqlgraph.Returning{Columns: link.Columns, Scan: func(rows dialect.Rows) error {
		values, err := _node.scanValues(link.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(link.Columns, values); err != nil {
			return err
		}

		_spec.ID.Value = _node.ID

		return nil
	}}
	return _node, _spec, nil
}

type LinkUpsertOne struct{ create *LinkCreate }

func (b *LinkCreate) OnConflict(columns ...ent.EntityColumn[entity.Link]) *LinkUpsertOne {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *LinkCreate) OnConflictConstraint(name string) *LinkUpsertOne {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *LinkCreate) OnConflictOptions(options ...sql.ConflictOption) *LinkUpsertOne {
	b.conflict = options
	return &LinkUpsertOne{create: b}
}

func (u *LinkUpsertOne) DoNothing() *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *LinkUpsertOne) DoSelect() *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *LinkUpsertOne) Ignore() *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *LinkUpsertOne) DoUpdate(set func(*LinkUpsert)) *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&LinkUpsert{UpdateSet: update}) }))
	return u
}

func (u *LinkUpsertOne) UpdateNewValues() *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case link.FieldID:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *LinkUpsertOne) Where(predicates ...ent.Predicate[entity.Link]) *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(link.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *LinkUpsertOne) UpdateWhere(predicates ...ent.Predicate[entity.Link]) *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(link.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *LinkUpsertOne) Save(ctx context.Context) (*Link, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for LinkCreate.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *LinkUpsertOne) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *LinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (u *LinkUpsertOne) ID(ctx context.Context) (id uuidc.UUIDC, err error) {
	node, err := u.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

func (u *LinkUpsertOne) IDX(ctx context.Context) uuidc.UUIDC {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

type LinkUpsert struct{ *sql.UpdateSet }

func (u *LinkUpsert) Set[T any](column ent.ColumnOf[entity.Link, T], value T) *LinkUpsert {
	switch column.Ref().Name {

	case link.FieldLinkInformation:

		encoded, err := json.Marshal(value)
		if err != nil {
			u.UpdateSet.AddError(err)
			return u
		}
		u.UpdateSet.Set(column.Ref().Name, json.RawMessage(encoded))

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Link is not settable", column.Ref().Name)})
	}
	return u
}

func (u *LinkUpsert) SetExpr[T any](column ent.ColumnOf[entity.Link, T], value ent.Expr[T]) *LinkUpsert {
	switch column.Ref().Name {

	case link.FieldLinkInformation:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Link is not settable", column.Ref().Name)})
	}
	return u
}

func (u *LinkUpsert) UpdateNewValue[T any](column ent.ColumnOf[entity.Link, T]) *LinkUpsert {
	switch column.Ref().Name {

	case link.FieldLinkInformation:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Link is not settable", column.Ref().Name)})
	}
	return u
}

func (u *LinkUpsert) Add[T ent.Number](column ent.ColumnOf[entity.Link, T], delta T) *LinkUpsert {
	switch column.Ref().Name {

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Link does not support addition", column.Ref().Name)})
	}
	return u
}

func (u *LinkUpsert) Clear[T any](column ent.ColumnOf[entity.Link, T]) *LinkUpsert {
	switch column.Ref().Name {

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Link is not nullable", column.Ref().Name)})
	}
	return u
}

type LinkCreateBulk struct {
	config
	err      error
	builders []*LinkCreate

	conflict []sql.ConflictOption
}

func (_c *LinkCreateBulk) Save(ctx context.Context) ([]*Link, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	nodes := make([]*Link, len(_c.builders))
	specs := make([]*sqlgraph.CreateSpec, len(nodes))
	for index, builder := range _c.builders {
		if builder.err != nil {
			return nil, builder.err
		}
		if err := builder.defaults(); err != nil {
			return nil, err
		}
		if err := builder.check(); err != nil {
			return nil, err
		}
		var err error
		nodes[index], specs[index], err = builder.createSpec()
		if err != nil {
			return nil, err
		}
	}
	if len(specs) == 0 {
		return nodes, nil
	}
	spec := &sqlgraph.BatchCreateSpec{Nodes: specs}

	spec.OnConflict = _c.conflict

	if err := sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	result := nodes[:0]
	for index, builder := range _c.builders {
		if specs[index].Skipped {
			continue
		}
		builder.mutation.id = &nodes[index].ID
		result = append(result, nodes[index])
	}
	return result, nil
}

func (b *LinkCreateBulk) SaveX(ctx context.Context) []*Link {
	nodes, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

func (b *LinkCreateBulk) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *LinkCreateBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

type LinkUpsertBulk struct{ create *LinkCreateBulk }

func (b *LinkCreateBulk) OnConflict(columns ...ent.EntityColumn[entity.Link]) *LinkUpsertBulk {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *LinkCreateBulk) OnConflictConstraint(name string) *LinkUpsertBulk {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *LinkCreateBulk) OnConflictOptions(options ...sql.ConflictOption) *LinkUpsertBulk {
	b.conflict = options
	return &LinkUpsertBulk{create: b}
}

func (u *LinkUpsertBulk) DoNothing() *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *LinkUpsertBulk) DoSelect() *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *LinkUpsertBulk) Ignore() *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *LinkUpsertBulk) DoUpdate(set func(*LinkUpsert)) *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&LinkUpsert{UpdateSet: update}) }))
	return u
}

func (u *LinkUpsertBulk) UpdateNewValues() *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case link.FieldID:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *LinkUpsertBulk) Where(predicates ...ent.Predicate[entity.Link]) *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(link.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *LinkUpsertBulk) UpdateWhere(predicates ...ent.Predicate[entity.Link]) *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(link.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *LinkUpsertBulk) Save(ctx context.Context) ([]*Link, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for LinkCreateBulk.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *LinkUpsertBulk) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *LinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}
