// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/customid/ent/entity"
	"github.com/neko-sc/ent/entc/integration/customid/ent/note"
	"github.com/neko-sc/ent/schema/field"
)

// NoteDelete is the builder for deleting a Note entity.
type NoteDelete struct {
	config

	mutation  *NoteMutation
	returning *sqlgraph.Returning
}

// Where appends a list predicates to the NoteDelete builder.
func (_d *NoteDelete) Where(predicates ...ent.Predicate[entity.Note]) *NoteDelete {
	_d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NoteDelete) Exec(ctx context.Context) (int, error) {
	return _d.sqlExec(ctx)
}

func (b *NoteDelete) Returning(ctx context.Context) ([]*Note, error) {
	nodes := make([]*Note, 0)
	b.returning = &sqlgraph.Returning{Columns: note.Columns, Scan: func(rows dialect.Rows) error {
		_node := &Note{config: b.config}
		values, err := _node.scanValues(note.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(note.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Exec(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NoteDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(note.Table, sqlgraph.NewFieldSpec(note.FieldID, field.TypeString))
	if ps := _d.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_spec.Returning = _d.returning
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// NoteDeleteOne is the builder for deleting a single Note entity.
type NoteDeleteOne struct {
	_d *NoteDelete
}

// Where appends a list predicates to the NoteDelete builder.
func (_d *NoteDeleteOne) Where(predicates ...ent.Predicate[entity.Note]) *NoteDeleteOne {
	_d._d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query.
func (_d *NoteDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{note.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NoteDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
