// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"github.com/neko-sc/ent/dialect/sql"
)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserOrErr calls the predicate only if the error is not nit.
func UserOrErr(p User, err error) User {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}
