// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/cascadelete/ent/comment"
	"github.com/neko-sc/ent/entc/integration/cascadelete/ent/entity"
	"github.com/neko-sc/ent/entc/integration/cascadelete/ent/post"
	"github.com/neko-sc/ent/schema/field"
)

type CommentCreate struct {
	config
	mutation    *CommentMutation
	err         error
	fromBuilder bool
	present     map[string]struct{}

	conflict []sql.ConflictOption
}

func (b *CommentCreate) Set[T any](column ent.ColumnOf[entity.Comment, T], value T) *CommentCreate {
	if b.err == nil {
		b.err = b.mutation.insert.set(column.Ref().Name, value)
	}
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b
}
func (b *CommentCreate) SetOptional[T any](column ent.ColumnOf[entity.Comment, T], value ent.Option[T]) *CommentCreate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.insert.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *CommentCreate) SetExpr[T any](column ent.ColumnOf[entity.Comment, T], value ent.Expr[T]) *CommentCreate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case comment.FieldText:

	case comment.FieldPostID:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Comment is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.insert.setExpr(column.Ref().Name, value.Render)
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b

}
func (b *CommentCreate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Comment, N, K], id K) *CommentCreate {
	if b.err == nil {
		b.err = b.mutation.insert.setEdge(edge.Ref().Name, id)
	}

	switch edge.Ref().Name {
	case comment.EdgePost:
		if b.present == nil {
			b.present = make(map[string]struct{})
		}
		b.present[comment.FieldPostID] = struct{}{}

	}

	return b
}
func (b *CommentCreate) AddIDs[N, K any](edge ent.Relation[entity.Comment, N, K], ids ...K) *CommentCreate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.insert.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CommentCreate) Mutation() *CommentMutation { return b.mutation }

func (b *CommentCreate) Insert() *CommentInsert { return b.mutation.insert }

func (b *CommentCreate) Save(ctx context.Context) (*Comment, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *CommentCreate) SaveX(ctx context.Context) *Comment {
	node, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

func (b *CommentCreate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CommentCreate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *CommentCreate) defaults() error {

	return nil
}

func (b *CommentCreate) check() error {
	if b.err != nil {
		return b.err
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[comment.FieldText]; b.fromBuilder && !present {
			return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Comment.text"`)}
		}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[comment.FieldPostID]; b.fromBuilder && !present {
			return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "Comment.post_id"`)}
		}
	}

	if len(b.mutation.insert.postIDs()) == 0 {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "Comment.post"`)}
	}

	return nil
}

func (_c *CommentCreate) sqlSave(ctx context.Context) (*Comment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	node, spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	_c.mutation.id = &node.ID
	return node, nil
}

func (_c *CommentCreate) createSpec() (*Comment, *sqlgraph.CreateSpec, error) {
	_node := &Comment{config: _c.config}
	_spec := sqlgraph.NewCreateSpec(comment.Table, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt))

	_spec.OnConflict = _c.conflict

	if _, present := _c.present[comment.FieldText]; !_c.fromBuilder || present {
		value := _c.mutation.insert.Text
		_spec.SetField(comment.FieldText, field.TypeString, value)
	}

	_spec.Expressions = _c.mutation.insert.expressions

	if nodes := _c.mutation.insert.postIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.PostTable,
			Columns: []string{comment.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	_spec.Returning = &sqlgraph.Returning{Columns: comment.Columns, Scan: func(rows dialect.Rows) error {
		values, err := _node.scanValues(comment.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(comment.Columns, values); err != nil {
			return err
		}

		_spec.ID.Value = _node.ID

		return nil
	}}
	return _node, _spec, nil
}

type CommentUpsertOne struct{ create *CommentCreate }

func (b *CommentCreate) OnConflict(columns ...ent.EntityColumn[entity.Comment]) *CommentUpsertOne {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *CommentCreate) OnConflictConstraint(name string) *CommentUpsertOne {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *CommentCreate) OnConflictOptions(options ...sql.ConflictOption) *CommentUpsertOne {
	b.conflict = options
	return &CommentUpsertOne{create: b}
}

func (u *CommentUpsertOne) DoNothing() *CommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *CommentUpsertOne) DoSelect() *CommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *CommentUpsertOne) Ignore() *CommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *CommentUpsertOne) DoUpdate(set func(*CommentUpsert)) *CommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&CommentUpsert{UpdateSet: update}) }))
	return u
}

func (u *CommentUpsertOne) UpdateNewValues() *CommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case comment.FieldID:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *CommentUpsertOne) Where(predicates ...ent.Predicate[entity.Comment]) *CommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(comment.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CommentUpsertOne) UpdateWhere(predicates ...ent.Predicate[entity.Comment]) *CommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(comment.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CommentUpsertOne) Save(ctx context.Context) (*Comment, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for CommentCreate.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *CommentUpsertOne) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *CommentUpsertOne) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (u *CommentUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

func (u *CommentUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

type CommentUpsert struct{ *sql.UpdateSet }

func (u *CommentUpsert) Set[T any](column ent.ColumnOf[entity.Comment, T], value T) *CommentUpsert {
	switch column.Ref().Name {

	case comment.FieldText:
		u.UpdateSet.Set(column.Ref().Name, value)

	case comment.FieldPostID:
		u.UpdateSet.Set(column.Ref().Name, value)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Comment is not settable", column.Ref().Name)})
	}
	return u
}

func (u *CommentUpsert) SetExpr[T any](column ent.ColumnOf[entity.Comment, T], value ent.Expr[T]) *CommentUpsert {
	switch column.Ref().Name {

	case comment.FieldText:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case comment.FieldPostID:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Comment is not settable", column.Ref().Name)})
	}
	return u
}

func (u *CommentUpsert) UpdateNewValue[T any](column ent.ColumnOf[entity.Comment, T]) *CommentUpsert {
	switch column.Ref().Name {

	case comment.FieldText:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case comment.FieldPostID:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Comment is not settable", column.Ref().Name)})
	}
	return u
}

func (u *CommentUpsert) Add[T ent.Number](column ent.ColumnOf[entity.Comment, T], delta T) *CommentUpsert {
	switch column.Ref().Name {

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Comment does not support addition", column.Ref().Name)})
	}
	return u
}

func (u *CommentUpsert) Clear[T any](column ent.ColumnOf[entity.Comment, T]) *CommentUpsert {
	switch column.Ref().Name {

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Comment is not nullable", column.Ref().Name)})
	}
	return u
}

type CommentCreateBulk struct {
	config
	err      error
	builders []*CommentCreate

	conflict []sql.ConflictOption
}

func (_c *CommentCreateBulk) Save(ctx context.Context) ([]*Comment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	nodes := make([]*Comment, len(_c.builders))
	specs := make([]*sqlgraph.CreateSpec, len(nodes))
	for index, builder := range _c.builders {
		if builder.err != nil {
			return nil, builder.err
		}
		if err := builder.defaults(); err != nil {
			return nil, err
		}
		if err := builder.check(); err != nil {
			return nil, err
		}
		var err error
		nodes[index], specs[index], err = builder.createSpec()
		if err != nil {
			return nil, err
		}
	}
	if len(specs) == 0 {
		return nodes, nil
	}
	spec := &sqlgraph.BatchCreateSpec{Nodes: specs}

	spec.OnConflict = _c.conflict

	if err := sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	result := nodes[:0]
	for index, builder := range _c.builders {
		if specs[index].Skipped {
			continue
		}
		builder.mutation.id = &nodes[index].ID
		result = append(result, nodes[index])
	}
	return result, nil
}

func (b *CommentCreateBulk) SaveX(ctx context.Context) []*Comment {
	nodes, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

func (b *CommentCreateBulk) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CommentCreateBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

type CommentUpsertBulk struct{ create *CommentCreateBulk }

func (b *CommentCreateBulk) OnConflict(columns ...ent.EntityColumn[entity.Comment]) *CommentUpsertBulk {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *CommentCreateBulk) OnConflictConstraint(name string) *CommentUpsertBulk {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *CommentCreateBulk) OnConflictOptions(options ...sql.ConflictOption) *CommentUpsertBulk {
	b.conflict = options
	return &CommentUpsertBulk{create: b}
}

func (u *CommentUpsertBulk) DoNothing() *CommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *CommentUpsertBulk) DoSelect() *CommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *CommentUpsertBulk) Ignore() *CommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *CommentUpsertBulk) DoUpdate(set func(*CommentUpsert)) *CommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&CommentUpsert{UpdateSet: update}) }))
	return u
}

func (u *CommentUpsertBulk) UpdateNewValues() *CommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case comment.FieldID:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *CommentUpsertBulk) Where(predicates ...ent.Predicate[entity.Comment]) *CommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(comment.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CommentUpsertBulk) UpdateWhere(predicates ...ent.Predicate[entity.Comment]) *CommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(comment.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *CommentUpsertBulk) Save(ctx context.Context) ([]*Comment, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for CommentCreateBulk.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *CommentUpsertBulk) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *CommentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}
