// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/entc/integration/cascadelete/ent/entity"
)

const (
	OpCreate    = ent.OpCreate
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne

	TypeComment = "Comment"

	TypePost = "Post"

	TypeUser = "User"
)

type CommentMutation struct {
	config
	op         ent.Op
	id         *int
	insert     *CommentInsert
	patch      *CommentPatch
	predicates []ent.Predicate[entity.Comment]
}

func newCommentMutation(c config, op ent.Op) *CommentMutation {
	m := &CommentMutation{config: c, op: op}
	if op.Is(OpCreate) {
		m.insert = &CommentInsert{}
	}
	if op.Is(OpUpdate | OpUpdateOne) {
		m.patch = &CommentPatch{}
	}
	return m
}

func (m *CommentMutation) Op() ent.Op { return m.op }

func (m *CommentMutation) Type() string { return "Comment" }

func (m *CommentMutation) Insert() *CommentInsert { return m.insert }

func (m *CommentMutation) Patch() *CommentPatch { return m.patch }

func (m *CommentMutation) Predicates() []ent.Predicate[entity.Comment] { return m.predicates }

func (m *CommentMutation) Where(predicates ...ent.Predicate[entity.Comment]) {
	m.predicates = append(m.predicates, predicates...)
}

func (m *CommentMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

func (m *CommentMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

func (m *CommentMutation) ID() (id int, exists bool) {
	if m.id != nil {
		return *m.id, true
	}

	return id, false
}

func (m *CommentMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		if id, exists := m.ID(); exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Comment.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

type PostMutation struct {
	config
	op         ent.Op
	id         *int
	insert     *PostInsert
	patch      *PostPatch
	predicates []ent.Predicate[entity.Post]
}

func newPostMutation(c config, op ent.Op) *PostMutation {
	m := &PostMutation{config: c, op: op}
	if op.Is(OpCreate) {
		m.insert = &PostInsert{}
	}
	if op.Is(OpUpdate | OpUpdateOne) {
		m.patch = &PostPatch{}
	}
	return m
}

func (m *PostMutation) Op() ent.Op { return m.op }

func (m *PostMutation) Type() string { return "Post" }

func (m *PostMutation) Insert() *PostInsert { return m.insert }

func (m *PostMutation) Patch() *PostPatch { return m.patch }

func (m *PostMutation) Predicates() []ent.Predicate[entity.Post] { return m.predicates }

func (m *PostMutation) Where(predicates ...ent.Predicate[entity.Post]) {
	m.predicates = append(m.predicates, predicates...)
}

func (m *PostMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

func (m *PostMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

func (m *PostMutation) ID() (id int, exists bool) {
	if m.id != nil {
		return *m.id, true
	}

	return id, false
}

func (m *PostMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		if id, exists := m.ID(); exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Post.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

type UserMutation struct {
	config
	op         ent.Op
	id         *int
	insert     *UserInsert
	patch      *UserPatch
	predicates []ent.Predicate[entity.User]
}

func newUserMutation(c config, op ent.Op) *UserMutation {
	m := &UserMutation{config: c, op: op}
	if op.Is(OpCreate) {
		m.insert = &UserInsert{}
	}
	if op.Is(OpUpdate | OpUpdateOne) {
		m.patch = &UserPatch{}
	}
	return m
}

func (m *UserMutation) Op() ent.Op { return m.op }

func (m *UserMutation) Type() string { return "User" }

func (m *UserMutation) Insert() *UserInsert { return m.insert }

func (m *UserMutation) Patch() *UserPatch { return m.patch }

func (m *UserMutation) Predicates() []ent.Predicate[entity.User] { return m.predicates }

func (m *UserMutation) Where(predicates ...ent.Predicate[entity.User]) {
	m.predicates = append(m.predicates, predicates...)
}

func (m *UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

func (m *UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

func (m *UserMutation) ID() (id int, exists bool) {
	if m.id != nil {
		return *m.id, true
	}

	return id, false
}

func (m *UserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		if id, exists := m.ID(); exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}
