// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package testschema

import (
	time2 "time"

	"github.com/neko-sc/ent/cache/internal/testschema/schema"
	"github.com/neko-sc/ent/cache/internal/testschema/user"
)

// The init function reads all schema descriptors with runtime code
// (default values and validators) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time2.Time)
}
