// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package post

import (
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/edgefield/ent/entity"
)

const (
	// Label holds the string label denoting the post type in the database.
	Label = "post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldAuthorID holds the string denoting the author_id field in the database.
	FieldAuthorID = "author_id"
	// EdgeAuthor holds the string denoting the author edge name in mutations.
	EdgeAuthor = "author"
	// Table holds the table name of the post in the database.
	Table = "posts"
	// AuthorTable is the table that holds the author relation/edge.
	AuthorTable = "posts"
	// AuthorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AuthorInverseTable = "users"
	// AuthorColumn is the table column denoting the author relation/edge.
	AuthorColumn = "author_id"
)

var (
	ID       = ent.OrderedColumn[entity.Post, int]{Table: Table, Name: FieldID}
	Text     = ent.StringColumn[entity.Post, string]{Table: Table, Name: FieldText}
	AuthorID = ent.OrderedColumn[entity.Post, int]{Table: Table, Name: FieldAuthorID}
	Author   = ent.NewUniqueRelation[entity.Post, entity.User, int](EdgeAuthor, newAuthorStep)
)

// Alias returns the columns of the posts table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias: name,
		ID:         ent.OrderedColumn[entity.Post, int]{Table: name, Name: FieldID},
		Text:       ent.StringColumn[entity.Post, string]{Table: name, Name: FieldText},
		AuthorID:   ent.OrderedColumn[entity.Post, int]{Table: name, Name: FieldAuthorID},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias string
	ID         ent.OrderedColumn[entity.Post, int]
	Text       ent.StringColumn[entity.Post, string]
	AuthorID   ent.OrderedColumn[entity.Post, int]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.Post]) ent.Predicate[entity.Post] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.Post]) ent.Predicate[entity.Post] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.Post]) ent.Predicate[entity.Post] { return ent.Not(predicate) }

// Columns holds all SQL columns for post fields.
var Columns = []string{
	FieldID,
	FieldText,
	FieldAuthorID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

func newAuthorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AuthorTable, AuthorColumn),
	)
}
