# Copyright 2019-2026 Facebook Inc.
# SPDX-License-Identifier: Apache-2.0

services:

  postgres16:
    image: postgres:16
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5436:5432

  postgres17:
    image: postgres:17
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5437:5432

  postgres18:
    image: postgres:18
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5438:5432
