// Code generated by ent, DO NOT EDIT.

package userauditlog

import (
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/examples/triggers/ent/entity"
)

const (
	// Label holds the string label denoting the userauditlog type in the database.
	Label = "user_audit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOperationType holds the string denoting the operation_type field in the database.
	FieldOperationType = "operation_type"
	// FieldOperationTime holds the string denoting the operation_time field in the database.
	FieldOperationTime = "operation_time"
	// FieldOldValue holds the string denoting the old_value field in the database.
	FieldOldValue = "old_value"
	// FieldNewValue holds the string denoting the new_value field in the database.
	FieldNewValue = "new_value"
	// Table holds the table name of the userauditlog in the database.
	Table = "user_audit_logs"
)

var (
	ID            = ent.OrderedColumn[entity.UserAuditLog, int]{Table: Table, Name: FieldID}
	OperationType = ent.StringColumn[entity.UserAuditLog, string]{Table: Table, Name: FieldOperationType}
	OperationTime = ent.StringColumn[entity.UserAuditLog, string]{Table: Table, Name: FieldOperationTime}
	OldValue      = ent.StringColumn[entity.UserAuditLog, string]{Table: Table, Name: FieldOldValue}
	NewValue      = ent.StringColumn[entity.UserAuditLog, string]{Table: Table, Name: FieldNewValue}
)

// Alias returns the columns of the user_audit_logs table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias:    name,
		ID:            ent.OrderedColumn[entity.UserAuditLog, int]{Table: name, Name: FieldID},
		OperationType: ent.StringColumn[entity.UserAuditLog, string]{Table: name, Name: FieldOperationType},
		OperationTime: ent.StringColumn[entity.UserAuditLog, string]{Table: name, Name: FieldOperationTime},
		OldValue:      ent.StringColumn[entity.UserAuditLog, string]{Table: name, Name: FieldOldValue},
		NewValue:      ent.StringColumn[entity.UserAuditLog, string]{Table: name, Name: FieldNewValue},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias    string
	ID            ent.OrderedColumn[entity.UserAuditLog, int]
	OperationType ent.StringColumn[entity.UserAuditLog, string]
	OperationTime ent.StringColumn[entity.UserAuditLog, string]
	OldValue      ent.StringColumn[entity.UserAuditLog, string]
	NewValue      ent.StringColumn[entity.UserAuditLog, string]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.UserAuditLog]) ent.Predicate[entity.UserAuditLog] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.UserAuditLog]) ent.Predicate[entity.UserAuditLog] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.UserAuditLog]) ent.Predicate[entity.UserAuditLog] {
	return ent.Not(predicate)
}

// Columns holds all SQL columns for userauditlog fields.
var Columns = []string{
	FieldID,
	FieldOperationType,
	FieldOperationTime,
	FieldOldValue,
	FieldNewValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
