// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package role

import (
	time2 "time"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/edgeschema/ent/entity"
)

const (
	// Label holds the string label denoting the role type in the database.
	Label = "role"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeRolesUsers holds the string denoting the roles_users edge name in mutations.
	EdgeRolesUsers = "roles_users"
	// Table holds the table name of the role in the database.
	Table = "roles"
	// UserTable is the table that holds the user relation/edge. The primary key declared below.
	UserTable = "role_users"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// RolesUsersTable is the table that holds the roles_users relation/edge.
	RolesUsersTable = "role_users"
	// RolesUsersInverseTable is the table name for the RoleUser entity.
	// It exists in this package in order to avoid circular dependency with the "roleuser" package.
	RolesUsersInverseTable = "role_users"
	// RolesUsersColumn is the table column denoting the roles_users relation/edge.
	RolesUsersColumn = "role_id"
)

var (
	ID         = ent.OrderedColumn[entity.Role, int]{Table: Table, Name: FieldID}
	Name       = ent.StringColumn[entity.Role, string]{Table: Table, Name: FieldName}
	CreatedAt  = ent.OrderedColumn[entity.Role, time2.Time]{Table: Table, Name: FieldCreatedAt}
	User       = ent.NewRelation[entity.Role, entity.User, int](EdgeUser, newUserStep)
	RolesUsers = ent.NewRelation[entity.Role, entity.RoleUser, any](EdgeRolesUsers, newRolesUsersStep)
)

// Alias returns the columns of the roles table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias: name,
		ID:         ent.OrderedColumn[entity.Role, int]{Table: name, Name: FieldID},
		Name:       ent.StringColumn[entity.Role, string]{Table: name, Name: FieldName},
		CreatedAt:  ent.OrderedColumn[entity.Role, time2.Time]{Table: name, Name: FieldCreatedAt},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias string
	ID         ent.OrderedColumn[entity.Role, int]
	Name       ent.StringColumn[entity.Role, string]
	CreatedAt  ent.OrderedColumn[entity.Role, time2.Time]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.Role]) ent.Predicate[entity.Role] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.Role]) ent.Predicate[entity.Role] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.Role]) ent.Predicate[entity.Role] { return ent.Not(predicate) }

// Columns holds all SQL columns for role fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCreatedAt,
}

var (
	// UserPrimaryKey and UserColumn2 are the table columns denoting the
	// primary key for the user relation (M2M).
	UserPrimaryKey = []string{"user_id", "role_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time2.Time
)

func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, UserTable, UserPrimaryKey...),
	)
}
func newRolesUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RolesUsersInverseTable, RolesUsersColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, RolesUsersTable, RolesUsersColumn),
	)
}
