// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package entv2

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/neko-sc/ent/entc/integration/migrate/entv2/migrate"

	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/pg"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/blog"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/car"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/conversion"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/customtype"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/group"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/media"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/pet"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/user"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/zoo"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Blog is the client for interacting with the Blog builders.
	Blog *BlogClient
	// Car is the client for interacting with the Car builders.
	Car *CarClient
	// Conversion is the client for interacting with the Conversion builders.
	Conversion *ConversionClient
	// CustomType is the client for interacting with the CustomType builders.
	CustomType *CustomTypeClient
	// Group is the client for interacting with the Group builders.
	Group *GroupClient
	// Media is the client for interacting with the Media builders.
	Media *MediaClient
	// Pet is the client for interacting with the Pet builders.
	Pet *PetClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// Zoo is the client for interacting with the Zoo builders.
	Zoo *ZooClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...ClientOption) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Blog = NewBlogClient(c.config)
	c.Car = NewCarClient(c.config)
	c.Conversion = NewConversionClient(c.config)
	c.CustomType = NewCustomTypeClient(c.config)
	c.Group = NewGroupClient(c.config)
	c.Media = NewMediaClient(c.config)
	c.Pet = NewPetClient(c.config)
	c.User = NewUserClient(c.config)
	c.Zoo = NewZooClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
	}
	// ClientOption function to configure the client.
	ClientOption func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...ClientOption) config {
	cfg := config{log: log.Println}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...ClientOption) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() ClientOption {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) ClientOption {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) ClientOption {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// ClientOptional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...ClientOption) (*Client, error) {
	switch driverName {
	case dialect.Postgres, dialect.SQLite:
		var drv dialect.Driver
		var err error
		if driverName == dialect.Postgres {
			drv, err = pg.Open(context.Background(), dataSourceName)
		} else {
			drv, err = sql.Open(dialect.Dialect(driverName), dataSourceName)
		}
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("entv2: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("entv2: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Blog:       NewBlogClient(cfg),
		Car:        NewCarClient(cfg),
		Conversion: NewConversionClient(cfg),
		CustomType: NewCustomTypeClient(cfg),
		Group:      NewGroupClient(cfg),
		Media:      NewMediaClient(cfg),
		Pet:        NewPetClient(cfg),
		User:       NewUserClient(cfg),
		Zoo:        NewZooClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Blog:       NewBlogClient(cfg),
		Car:        NewCarClient(cfg),
		Conversion: NewConversionClient(cfg),
		CustomType: NewCustomTypeClient(cfg),
		Group:      NewGroupClient(cfg),
		Media:      NewMediaClient(cfg),
		Pet:        NewPetClient(cfg),
		User:       NewUserClient(cfg),
		Zoo:        NewZooClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Blog.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Mutate executes the given mutation.
func (c *Client) Mutate(ctx context.Context, m Mutation) (any, error) {
	switch m := m.(type) {
	case *BlogMutation:
		return c.Blog.mutate(ctx, m)
	case *CarMutation:
		return c.Car.mutate(ctx, m)
	case *ConversionMutation:
		return c.Conversion.mutate(ctx, m)
	case *CustomTypeMutation:
		return c.CustomType.mutate(ctx, m)
	case *GroupMutation:
		return c.Group.mutate(ctx, m)
	case *MediaMutation:
		return c.Media.mutate(ctx, m)
	case *PetMutation:
		return c.Pet.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *ZooMutation:
		return c.Zoo.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("entv2: unknown mutation type %T", m)
	}
}

// BlogClient is a client for the Blog schema.
type BlogClient struct {
	config
}

// NewBlogClient returns a client for the Blog from the given config.
func NewBlogClient(c config) *BlogClient {
	return &BlogClient{config: c}
}

// Create returns a builder for creating a Blog entity.
func (c *BlogClient) Create() *BlogCreate {
	mutation := newBlogMutation(c.config, OpCreate)
	return &BlogCreate{config: c.config, mutation: mutation, fromBuilder: true}
}

func (c *BlogClient) Insert(value BlogInsert) *BlogCreate {
	mutation := newBlogMutation(c.config, OpCreate)
	mutation.insert = &value
	return &BlogCreate{config: c.config, mutation: mutation}
}

func (c *BlogClient) InsertBulk(values ...BlogInsert) *BlogCreateBulk {
	builders := make([]*BlogCreate, len(values))
	for index := range values {
		builders[index] = c.Insert(values[index])
	}
	return c.CreateBulk(builders...)
}

// CreateBulk returns a builder for creating a bulk of Blog entities.
func (c *BlogClient) CreateBulk(builders ...*BlogCreate) *BlogCreateBulk {
	return &BlogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BlogClient) MapCreateBulk(slice any, setFunc func(*BlogCreate, int)) *BlogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BlogCreateBulk{err: fmt.Errorf("calling to BlogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BlogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BlogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Blog.
func (c *BlogClient) Update() *BlogUpdate {
	mutation := newBlogMutation(c.config, OpUpdate)
	return &BlogUpdate{config: c.config, mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BlogClient) UpdateOne(_m *Blog) *BlogUpdateOne {
	return c.UpdateOneID(_m.ID)

}

// UpdateOneID returns an update builder for the given id.
func (c *BlogClient) UpdateOneID(id int) *BlogUpdateOne {
	mutation := newBlogMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &BlogUpdateOne{config: c.config, mutation: mutation}
}

// Delete returns a delete builder for Blog.
func (c *BlogClient) Delete() *BlogDelete {
	mutation := newBlogMutation(c.config, OpDelete)
	return &BlogDelete{config: c.config, mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BlogClient) DeleteOne(_m *Blog) *BlogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BlogClient) DeleteOneID(id int) *BlogDeleteOne {
	builder := c.Delete().Where(blog.ID.EQ(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BlogDeleteOne{builder}
}

// Query returns a query builder for Blog.
func (c *BlogClient) Query() *BlogQuery {
	return &BlogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBlog},
	}
}

// Get returns a Blog entity by its id.
func (c *BlogClient) Get(ctx context.Context, id int) (*Blog, error) {
	return c.Query().Where(blog.ID.EQ(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BlogClient) GetX(ctx context.Context, id int) *Blog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAdmins queries the admins edge of a Blog.
func (c *BlogClient) QueryAdmins(_m *Blog) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(blog.Table, blog.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, blog.AdminsTable, blog.AdminsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

func (c *BlogClient) mutate(ctx context.Context, m *BlogMutation) (any, error) {
	switch m.Op() {
	case OpCreate:
		return (&BlogCreate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BlogUpdate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BlogUpdateOne{config: c.config, mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BlogDelete{config: c.config, mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv2: unknown Blog mutation op: %q", m.Op())
	}
}

// CarClient is a client for the Car schema.
type CarClient struct {
	config
}

// NewCarClient returns a client for the Car from the given config.
func NewCarClient(c config) *CarClient {
	return &CarClient{config: c}
}

// Create returns a builder for creating a Car entity.
func (c *CarClient) Create() *CarCreate {
	mutation := newCarMutation(c.config, OpCreate)
	return &CarCreate{config: c.config, mutation: mutation, fromBuilder: true}
}

func (c *CarClient) Insert(value CarInsert) *CarCreate {
	mutation := newCarMutation(c.config, OpCreate)
	mutation.insert = &value
	return &CarCreate{config: c.config, mutation: mutation}
}

func (c *CarClient) InsertBulk(values ...CarInsert) *CarCreateBulk {
	builders := make([]*CarCreate, len(values))
	for index := range values {
		builders[index] = c.Insert(values[index])
	}
	return c.CreateBulk(builders...)
}

// CreateBulk returns a builder for creating a bulk of Car entities.
func (c *CarClient) CreateBulk(builders ...*CarCreate) *CarCreateBulk {
	return &CarCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CarClient) MapCreateBulk(slice any, setFunc func(*CarCreate, int)) *CarCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CarCreateBulk{err: fmt.Errorf("calling to CarClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CarCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CarCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Car.
func (c *CarClient) Update() *CarUpdate {
	mutation := newCarMutation(c.config, OpUpdate)
	return &CarUpdate{config: c.config, mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CarClient) UpdateOne(_m *Car) *CarUpdateOne {
	return c.UpdateOneID(_m.ID)

}

// UpdateOneID returns an update builder for the given id.
func (c *CarClient) UpdateOneID(id int) *CarUpdateOne {
	mutation := newCarMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &CarUpdateOne{config: c.config, mutation: mutation}
}

// Delete returns a delete builder for Car.
func (c *CarClient) Delete() *CarDelete {
	mutation := newCarMutation(c.config, OpDelete)
	return &CarDelete{config: c.config, mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CarClient) DeleteOne(_m *Car) *CarDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CarClient) DeleteOneID(id int) *CarDeleteOne {
	builder := c.Delete().Where(car.ID.EQ(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CarDeleteOne{builder}
}

// Query returns a query builder for Car.
func (c *CarClient) Query() *CarQuery {
	return &CarQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCar},
	}
}

// Get returns a Car entity by its id.
func (c *CarClient) Get(ctx context.Context, id int) (*Car, error) {
	return c.Query().Where(car.ID.EQ(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CarClient) GetX(ctx context.Context, id int) *Car {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a Car.
func (c *CarClient) QueryOwner(_m *Car) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(car.Table, car.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, car.OwnerTable, car.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

func (c *CarClient) mutate(ctx context.Context, m *CarMutation) (any, error) {
	switch m.Op() {
	case OpCreate:
		return (&CarCreate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CarUpdate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CarUpdateOne{config: c.config, mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CarDelete{config: c.config, mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv2: unknown Car mutation op: %q", m.Op())
	}
}

// ConversionClient is a client for the Conversion schema.
type ConversionClient struct {
	config
}

// NewConversionClient returns a client for the Conversion from the given config.
func NewConversionClient(c config) *ConversionClient {
	return &ConversionClient{config: c}
}

// Create returns a builder for creating a Conversion entity.
func (c *ConversionClient) Create() *ConversionCreate {
	mutation := newConversionMutation(c.config, OpCreate)
	return &ConversionCreate{config: c.config, mutation: mutation, fromBuilder: true}
}

func (c *ConversionClient) Insert(value ConversionInsert) *ConversionCreate {
	mutation := newConversionMutation(c.config, OpCreate)
	mutation.insert = &value
	return &ConversionCreate{config: c.config, mutation: mutation}
}

func (c *ConversionClient) InsertBulk(values ...ConversionInsert) *ConversionCreateBulk {
	builders := make([]*ConversionCreate, len(values))
	for index := range values {
		builders[index] = c.Insert(values[index])
	}
	return c.CreateBulk(builders...)
}

// CreateBulk returns a builder for creating a bulk of Conversion entities.
func (c *ConversionClient) CreateBulk(builders ...*ConversionCreate) *ConversionCreateBulk {
	return &ConversionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ConversionClient) MapCreateBulk(slice any, setFunc func(*ConversionCreate, int)) *ConversionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ConversionCreateBulk{err: fmt.Errorf("calling to ConversionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ConversionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ConversionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Conversion.
func (c *ConversionClient) Update() *ConversionUpdate {
	mutation := newConversionMutation(c.config, OpUpdate)
	return &ConversionUpdate{config: c.config, mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ConversionClient) UpdateOne(_m *Conversion) *ConversionUpdateOne {
	return c.UpdateOneID(_m.ID)

}

// UpdateOneID returns an update builder for the given id.
func (c *ConversionClient) UpdateOneID(id int) *ConversionUpdateOne {
	mutation := newConversionMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &ConversionUpdateOne{config: c.config, mutation: mutation}
}

// Delete returns a delete builder for Conversion.
func (c *ConversionClient) Delete() *ConversionDelete {
	mutation := newConversionMutation(c.config, OpDelete)
	return &ConversionDelete{config: c.config, mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ConversionClient) DeleteOne(_m *Conversion) *ConversionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ConversionClient) DeleteOneID(id int) *ConversionDeleteOne {
	builder := c.Delete().Where(conversion.ID.EQ(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ConversionDeleteOne{builder}
}

// Query returns a query builder for Conversion.
func (c *ConversionClient) Query() *ConversionQuery {
	return &ConversionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeConversion},
	}
}

// Get returns a Conversion entity by its id.
func (c *ConversionClient) Get(ctx context.Context, id int) (*Conversion, error) {
	return c.Query().Where(conversion.ID.EQ(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ConversionClient) GetX(ctx context.Context, id int) *Conversion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

func (c *ConversionClient) mutate(ctx context.Context, m *ConversionMutation) (any, error) {
	switch m.Op() {
	case OpCreate:
		return (&ConversionCreate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ConversionUpdate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ConversionUpdateOne{config: c.config, mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ConversionDelete{config: c.config, mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv2: unknown Conversion mutation op: %q", m.Op())
	}
}

// CustomTypeClient is a client for the CustomType schema.
type CustomTypeClient struct {
	config
}

// NewCustomTypeClient returns a client for the CustomType from the given config.
func NewCustomTypeClient(c config) *CustomTypeClient {
	return &CustomTypeClient{config: c}
}

// Create returns a builder for creating a CustomType entity.
func (c *CustomTypeClient) Create() *CustomTypeCreate {
	mutation := newCustomTypeMutation(c.config, OpCreate)
	return &CustomTypeCreate{config: c.config, mutation: mutation, fromBuilder: true}
}

func (c *CustomTypeClient) Insert(value CustomTypeInsert) *CustomTypeCreate {
	mutation := newCustomTypeMutation(c.config, OpCreate)
	mutation.insert = &value
	return &CustomTypeCreate{config: c.config, mutation: mutation}
}

func (c *CustomTypeClient) InsertBulk(values ...CustomTypeInsert) *CustomTypeCreateBulk {
	builders := make([]*CustomTypeCreate, len(values))
	for index := range values {
		builders[index] = c.Insert(values[index])
	}
	return c.CreateBulk(builders...)
}

// CreateBulk returns a builder for creating a bulk of CustomType entities.
func (c *CustomTypeClient) CreateBulk(builders ...*CustomTypeCreate) *CustomTypeCreateBulk {
	return &CustomTypeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CustomTypeClient) MapCreateBulk(slice any, setFunc func(*CustomTypeCreate, int)) *CustomTypeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CustomTypeCreateBulk{err: fmt.Errorf("calling to CustomTypeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CustomTypeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CustomTypeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CustomType.
func (c *CustomTypeClient) Update() *CustomTypeUpdate {
	mutation := newCustomTypeMutation(c.config, OpUpdate)
	return &CustomTypeUpdate{config: c.config, mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CustomTypeClient) UpdateOne(_m *CustomType) *CustomTypeUpdateOne {
	return c.UpdateOneID(_m.ID)

}

// UpdateOneID returns an update builder for the given id.
func (c *CustomTypeClient) UpdateOneID(id int) *CustomTypeUpdateOne {
	mutation := newCustomTypeMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &CustomTypeUpdateOne{config: c.config, mutation: mutation}
}

// Delete returns a delete builder for CustomType.
func (c *CustomTypeClient) Delete() *CustomTypeDelete {
	mutation := newCustomTypeMutation(c.config, OpDelete)
	return &CustomTypeDelete{config: c.config, mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CustomTypeClient) DeleteOne(_m *CustomType) *CustomTypeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CustomTypeClient) DeleteOneID(id int) *CustomTypeDeleteOne {
	builder := c.Delete().Where(customtype.ID.EQ(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CustomTypeDeleteOne{builder}
}

// Query returns a query builder for CustomType.
func (c *CustomTypeClient) Query() *CustomTypeQuery {
	return &CustomTypeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCustomType},
	}
}

// Get returns a CustomType entity by its id.
func (c *CustomTypeClient) Get(ctx context.Context, id int) (*CustomType, error) {
	return c.Query().Where(customtype.ID.EQ(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CustomTypeClient) GetX(ctx context.Context, id int) *CustomType {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

func (c *CustomTypeClient) mutate(ctx context.Context, m *CustomTypeMutation) (any, error) {
	switch m.Op() {
	case OpCreate:
		return (&CustomTypeCreate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CustomTypeUpdate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CustomTypeUpdateOne{config: c.config, mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CustomTypeDelete{config: c.config, mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv2: unknown CustomType mutation op: %q", m.Op())
	}
}

// GroupClient is a client for the Group schema.
type GroupClient struct {
	config
}

// NewGroupClient returns a client for the Group from the given config.
func NewGroupClient(c config) *GroupClient {
	return &GroupClient{config: c}
}

// Create returns a builder for creating a Group entity.
func (c *GroupClient) Create() *GroupCreate {
	mutation := newGroupMutation(c.config, OpCreate)
	return &GroupCreate{config: c.config, mutation: mutation, fromBuilder: true}
}

func (c *GroupClient) Insert(value GroupInsert) *GroupCreate {
	mutation := newGroupMutation(c.config, OpCreate)
	mutation.insert = &value
	return &GroupCreate{config: c.config, mutation: mutation}
}

func (c *GroupClient) InsertBulk(values ...GroupInsert) *GroupCreateBulk {
	builders := make([]*GroupCreate, len(values))
	for index := range values {
		builders[index] = c.Insert(values[index])
	}
	return c.CreateBulk(builders...)
}

// CreateBulk returns a builder for creating a bulk of Group entities.
func (c *GroupClient) CreateBulk(builders ...*GroupCreate) *GroupCreateBulk {
	return &GroupCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GroupClient) MapCreateBulk(slice any, setFunc func(*GroupCreate, int)) *GroupCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GroupCreateBulk{err: fmt.Errorf("calling to GroupClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GroupCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GroupCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Group.
func (c *GroupClient) Update() *GroupUpdate {
	mutation := newGroupMutation(c.config, OpUpdate)
	return &GroupUpdate{config: c.config, mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GroupClient) UpdateOne(_m *Group) *GroupUpdateOne {
	return c.UpdateOneID(_m.ID)

}

// UpdateOneID returns an update builder for the given id.
func (c *GroupClient) UpdateOneID(id int) *GroupUpdateOne {
	mutation := newGroupMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &GroupUpdateOne{config: c.config, mutation: mutation}
}

// Delete returns a delete builder for Group.
func (c *GroupClient) Delete() *GroupDelete {
	mutation := newGroupMutation(c.config, OpDelete)
	return &GroupDelete{config: c.config, mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GroupClient) DeleteOne(_m *Group) *GroupDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GroupClient) DeleteOneID(id int) *GroupDeleteOne {
	builder := c.Delete().Where(group.ID.EQ(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GroupDeleteOne{builder}
}

// Query returns a query builder for Group.
func (c *GroupClient) Query() *GroupQuery {
	return &GroupQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGroup},
	}
}

// Get returns a Group entity by its id.
func (c *GroupClient) Get(ctx context.Context, id int) (*Group, error) {
	return c.Query().Where(group.ID.EQ(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GroupClient) GetX(ctx context.Context, id int) *Group {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

func (c *GroupClient) mutate(ctx context.Context, m *GroupMutation) (any, error) {
	switch m.Op() {
	case OpCreate:
		return (&GroupCreate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GroupUpdate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GroupUpdateOne{config: c.config, mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GroupDelete{config: c.config, mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv2: unknown Group mutation op: %q", m.Op())
	}
}

// MediaClient is a client for the Media schema.
type MediaClient struct {
	config
}

// NewMediaClient returns a client for the Media from the given config.
func NewMediaClient(c config) *MediaClient {
	return &MediaClient{config: c}
}

// Create returns a builder for creating a Media entity.
func (c *MediaClient) Create() *MediaCreate {
	mutation := newMediaMutation(c.config, OpCreate)
	return &MediaCreate{config: c.config, mutation: mutation, fromBuilder: true}
}

func (c *MediaClient) Insert(value MediaInsert) *MediaCreate {
	mutation := newMediaMutation(c.config, OpCreate)
	mutation.insert = &value
	return &MediaCreate{config: c.config, mutation: mutation}
}

func (c *MediaClient) InsertBulk(values ...MediaInsert) *MediaCreateBulk {
	builders := make([]*MediaCreate, len(values))
	for index := range values {
		builders[index] = c.Insert(values[index])
	}
	return c.CreateBulk(builders...)
}

// CreateBulk returns a builder for creating a bulk of Media entities.
func (c *MediaClient) CreateBulk(builders ...*MediaCreate) *MediaCreateBulk {
	return &MediaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MediaClient) MapCreateBulk(slice any, setFunc func(*MediaCreate, int)) *MediaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MediaCreateBulk{err: fmt.Errorf("calling to MediaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MediaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MediaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Media.
func (c *MediaClient) Update() *MediaUpdate {
	mutation := newMediaMutation(c.config, OpUpdate)
	return &MediaUpdate{config: c.config, mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MediaClient) UpdateOne(_m *Media) *MediaUpdateOne {
	return c.UpdateOneID(_m.ID)

}

// UpdateOneID returns an update builder for the given id.
func (c *MediaClient) UpdateOneID(id int) *MediaUpdateOne {
	mutation := newMediaMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &MediaUpdateOne{config: c.config, mutation: mutation}
}

// Delete returns a delete builder for Media.
func (c *MediaClient) Delete() *MediaDelete {
	mutation := newMediaMutation(c.config, OpDelete)
	return &MediaDelete{config: c.config, mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MediaClient) DeleteOne(_m *Media) *MediaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MediaClient) DeleteOneID(id int) *MediaDeleteOne {
	builder := c.Delete().Where(media.ID.EQ(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MediaDeleteOne{builder}
}

// Query returns a query builder for Media.
func (c *MediaClient) Query() *MediaQuery {
	return &MediaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMedia},
	}
}

// Get returns a Media entity by its id.
func (c *MediaClient) Get(ctx context.Context, id int) (*Media, error) {
	return c.Query().Where(media.ID.EQ(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MediaClient) GetX(ctx context.Context, id int) *Media {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

func (c *MediaClient) mutate(ctx context.Context, m *MediaMutation) (any, error) {
	switch m.Op() {
	case OpCreate:
		return (&MediaCreate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MediaUpdate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MediaUpdateOne{config: c.config, mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MediaDelete{config: c.config, mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv2: unknown Media mutation op: %q", m.Op())
	}
}

// PetClient is a client for the Pet schema.
type PetClient struct {
	config
}

// NewPetClient returns a client for the Pet from the given config.
func NewPetClient(c config) *PetClient {
	return &PetClient{config: c}
}

// Create returns a builder for creating a Pet entity.
func (c *PetClient) Create() *PetCreate {
	mutation := newPetMutation(c.config, OpCreate)
	return &PetCreate{config: c.config, mutation: mutation, fromBuilder: true}
}

func (c *PetClient) Insert(value PetInsert) *PetCreate {
	mutation := newPetMutation(c.config, OpCreate)
	mutation.insert = &value
	return &PetCreate{config: c.config, mutation: mutation}
}

func (c *PetClient) InsertBulk(values ...PetInsert) *PetCreateBulk {
	builders := make([]*PetCreate, len(values))
	for index := range values {
		builders[index] = c.Insert(values[index])
	}
	return c.CreateBulk(builders...)
}

// CreateBulk returns a builder for creating a bulk of Pet entities.
func (c *PetClient) CreateBulk(builders ...*PetCreate) *PetCreateBulk {
	return &PetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PetClient) MapCreateBulk(slice any, setFunc func(*PetCreate, int)) *PetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PetCreateBulk{err: fmt.Errorf("calling to PetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Pet.
func (c *PetClient) Update() *PetUpdate {
	mutation := newPetMutation(c.config, OpUpdate)
	return &PetUpdate{config: c.config, mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PetClient) UpdateOne(_m *Pet) *PetUpdateOne {
	return c.UpdateOneID(_m.ID)

}

// UpdateOneID returns an update builder for the given id.
func (c *PetClient) UpdateOneID(id int) *PetUpdateOne {
	mutation := newPetMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &PetUpdateOne{config: c.config, mutation: mutation}
}

// Delete returns a delete builder for Pet.
func (c *PetClient) Delete() *PetDelete {
	mutation := newPetMutation(c.config, OpDelete)
	return &PetDelete{config: c.config, mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PetClient) DeleteOne(_m *Pet) *PetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PetClient) DeleteOneID(id int) *PetDeleteOne {
	builder := c.Delete().Where(pet.ID.EQ(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PetDeleteOne{builder}
}

// Query returns a query builder for Pet.
func (c *PetClient) Query() *PetQuery {
	return &PetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePet},
	}
}

// Get returns a Pet entity by its id.
func (c *PetClient) Get(ctx context.Context, id int) (*Pet, error) {
	return c.Query().Where(pet.ID.EQ(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PetClient) GetX(ctx context.Context, id int) *Pet {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a Pet.
func (c *PetClient) QueryOwner(_m *Pet) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, pet.OwnerTable, pet.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

func (c *PetClient) mutate(ctx context.Context, m *PetMutation) (any, error) {
	switch m.Op() {
	case OpCreate:
		return (&PetCreate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PetUpdate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PetUpdateOne{config: c.config, mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PetDelete{config: c.config, mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv2: unknown Pet mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, mutation: mutation, fromBuilder: true}
}

func (c *UserClient) Insert(value UserInsert) *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	mutation.insert = &value
	return &UserCreate{config: c.config, mutation: mutation}
}

func (c *UserClient) InsertBulk(values ...UserInsert) *UserCreateBulk {
	builders := make([]*UserCreate, len(values))
	for index := range values {
		builders[index] = c.Insert(values[index])
	}
	return c.CreateBulk(builders...)
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	return c.UpdateOneID(_m.ID)

}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &UserUpdateOne{config: c.config, mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID.EQ(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID.EQ(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCar queries the car edge of a User.
func (c *UserClient) QueryCar(_m *User) *CarQuery {
	query := (&CarClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(car.Table, car.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.CarTable, user.CarColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPets queries the pets edge of a User.
func (c *UserClient) QueryPets(_m *User) *PetQuery {
	query := (&PetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, user.PetsTable, user.PetsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFriends queries the friends edge of a User.
func (c *UserClient) QueryFriends(_m *User) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, user.FriendsTable, user.FriendsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (any, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv2: unknown User mutation op: %q", m.Op())
	}
}

// ZooClient is a client for the Zoo schema.
type ZooClient struct {
	config
}

// NewZooClient returns a client for the Zoo from the given config.
func NewZooClient(c config) *ZooClient {
	return &ZooClient{config: c}
}

// Create returns a builder for creating a Zoo entity.
func (c *ZooClient) Create() *ZooCreate {
	mutation := newZooMutation(c.config, OpCreate)
	return &ZooCreate{config: c.config, mutation: mutation, fromBuilder: true}
}

func (c *ZooClient) Insert(value ZooInsert) *ZooCreate {
	mutation := newZooMutation(c.config, OpCreate)
	mutation.insert = &value
	return &ZooCreate{config: c.config, mutation: mutation}
}

func (c *ZooClient) InsertBulk(values ...ZooInsert) *ZooCreateBulk {
	builders := make([]*ZooCreate, len(values))
	for index := range values {
		builders[index] = c.Insert(values[index])
	}
	return c.CreateBulk(builders...)
}

// CreateBulk returns a builder for creating a bulk of Zoo entities.
func (c *ZooClient) CreateBulk(builders ...*ZooCreate) *ZooCreateBulk {
	return &ZooCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ZooClient) MapCreateBulk(slice any, setFunc func(*ZooCreate, int)) *ZooCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ZooCreateBulk{err: fmt.Errorf("calling to ZooClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ZooCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ZooCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Zoo.
func (c *ZooClient) Update() *ZooUpdate {
	mutation := newZooMutation(c.config, OpUpdate)
	return &ZooUpdate{config: c.config, mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ZooClient) UpdateOne(_m *Zoo) *ZooUpdateOne {
	return c.UpdateOneID(_m.ID)

}

// UpdateOneID returns an update builder for the given id.
func (c *ZooClient) UpdateOneID(id int) *ZooUpdateOne {
	mutation := newZooMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &ZooUpdateOne{config: c.config, mutation: mutation}
}

// Delete returns a delete builder for Zoo.
func (c *ZooClient) Delete() *ZooDelete {
	mutation := newZooMutation(c.config, OpDelete)
	return &ZooDelete{config: c.config, mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ZooClient) DeleteOne(_m *Zoo) *ZooDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ZooClient) DeleteOneID(id int) *ZooDeleteOne {
	builder := c.Delete().Where(zoo.ID.EQ(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ZooDeleteOne{builder}
}

// Query returns a query builder for Zoo.
func (c *ZooClient) Query() *ZooQuery {
	return &ZooQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeZoo},
	}
}

// Get returns a Zoo entity by its id.
func (c *ZooClient) Get(ctx context.Context, id int) (*Zoo, error) {
	return c.Query().Where(zoo.ID.EQ(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ZooClient) GetX(ctx context.Context, id int) *Zoo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

func (c *ZooClient) mutate(ctx context.Context, m *ZooMutation) (any, error) {
	switch m.Op() {
	case OpCreate:
		return (&ZooCreate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ZooUpdate{config: c.config, mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ZooUpdateOne{config: c.config, mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ZooDelete{config: c.config, mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv2: unknown Zoo mutation op: %q", m.Op())
	}
}

// Driver returns the driver bound to this client or transaction.
func (c *Client) Driver() dialect.Driver { return c.config.driver }
