// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package entv2

import (
	"fmt"
	"strings"
	"time"
	time2 "time"

	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/customtype"
)

// CustomType is the model entity for the CustomType schema.
type CustomType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Custom holds the value of the "custom" field.
	Custom string `json:"custom,omitempty"`
	// Tz0 holds the value of the "tz0" field.
	Tz0 time2.Time `json:"tz0,omitempty"`
	// Tz3 holds the value of the "tz3" field.
	Tz3 time2.Time `json:"tz3,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CustomType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case customtype.FieldID:
			values[i] = new(*int)
		case customtype.FieldCustom:
			values[i] = new(*string)
		case customtype.FieldTz0, customtype.FieldTz3:
			values[i] = new(*time2.Time)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CustomType fields.
func (_m *CustomType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case customtype.FieldID:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil && *value != nil {
				_m.ID = **value
			}
		case customtype.FieldCustom:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field custom", values[i])
			} else if value != nil && *value != nil {
				_m.Custom = **value
			}
		case customtype.FieldTz0:

			if value, ok := values[i].(**time2.Time); !ok {
				return fmt.Errorf("unexpected type %T for field tz0", values[i])
			} else if value != nil && *value != nil {
				_m.Tz0 = **value
			}
		case customtype.FieldTz3:

			if value, ok := values[i].(**time2.Time); !ok {
				return fmt.Errorf("unexpected type %T for field tz3", values[i])
			} else if value != nil && *value != nil {
				_m.Tz3 = **value
			}
		}
	}
	return nil
}

// Update returns a builder for updating this CustomType.
// Note that you need to call CustomType.Unwrap() before calling this method if this CustomType
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CustomType) Update() *CustomTypeUpdateOne {
	return NewCustomTypeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CustomType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CustomType) Unwrap() *CustomType {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("entv2: CustomType is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CustomType) String() string {
	var builder strings.Builder
	builder.WriteString("CustomType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("custom=")
	builder.WriteString(_m.Custom)
	builder.WriteString(", ")
	builder.WriteString("tz0=")
	builder.WriteString(_m.Tz0.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tz3=")
	builder.WriteString(_m.Tz3.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CustomTypes is a parsable slice of CustomType.
type CustomTypes []*CustomType
