// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package entv2

import (
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/media"
)

// MediaInsert is the write representation of a Media creation.
type MediaInsert struct {
	Source      ent.Option[string] `json:"source,omitzero"`
	SourceURI   ent.Option[string] `json:"source_uri,omitzero"`
	Text        ent.Option[string] `json:"text,omitzero"`
	expressions map[string]func(*sql.Builder)
}

// MediaPatch is the write representation of a Media update.
type MediaPatch struct {
	Source       ent.Option[string] `json:"source,omitzero"`
	SourceURI    ent.Option[string] `json:"source_uri,omitzero"`
	Text         ent.Option[string] `json:"text,omitzero"`
	expressions  map[string]func(*sql.Builder)
	clearedEdges map[string]bool
}

func (i *MediaInsert) set(column string, value any) error {
	switch column {

	case media.FieldSource:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Media", value, column)}
		}
		i.Source = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case media.FieldSourceURI:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Media", value, column)}
		}
		i.SourceURI = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case media.FieldText:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Media", value, column)}
		}
		i.Text = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Media is not settable", column)}
}

func (i *MediaInsert) setNull(column string) error {
	switch column {

	case media.FieldSource:
		i.Source = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case media.FieldSourceURI:
		i.SourceURI = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case media.FieldText:
		i.Text = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Media is not nullable", column)}
}

func (i *MediaInsert) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *MediaInsert) setEdge(edge string, id any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Media is not settable", edge)}
}

func (i *MediaInsert) addIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Media does not accept IDs", edge)}
}

func (i *MediaPatch) set(column string, value any) error {
	switch column {

	case media.FieldSource:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Media", value, column)}
		}
		i.Source = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case media.FieldSourceURI:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Media", value, column)}
		}
		i.SourceURI = ent.Some(v)

		delete(i.expressions, column)
		return nil

	case media.FieldText:
		v, ok := value.(string)
		if !ok {
			return &ValidationError{Name: column, err: fmt.Errorf("ent: unexpected type %T for field %q of Media", value, column)}
		}
		i.Text = ent.Some(v)

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Media is not settable", column)}
}

func (i *MediaPatch) setNull(column string) error {
	switch column {

	case media.FieldSource:
		i.Source = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case media.FieldSourceURI:
		i.SourceURI = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	case media.FieldText:
		i.Text = ent.Null[string]()

		delete(i.expressions, column)
		return nil

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Media is not nullable", column)}
}

func (i *MediaPatch) setExpr(column string, render func(*sql.Builder)) {
	if i.expressions == nil {
		i.expressions = make(map[string]func(*sql.Builder))
	}
	i.expressions[column] = render
}

func (i *MediaPatch) setEdge(edge string, id any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Media is not settable", edge)}
}

func (i *MediaPatch) addIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Media does not accept IDs", edge)}
}

func (p *MediaPatch) add(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Media does not support addition", column)}
}

func (p *MediaPatch) appendValues(column string, value any) error {
	switch column {

	}
	return &ValidationError{Name: column, err: fmt.Errorf("ent: field %q of Media does not support append", column)}
}

func (p *MediaPatch) removeIDs(edge string, ids ...any) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Media does not support removal", edge)}
}

func (p *MediaPatch) clearEdge(edge string) error {
	switch edge {

	}
	return &ValidationError{Name: edge, err: fmt.Errorf("ent: edge %q of Media cannot be cleared", edge)}
}

func (p *MediaPatch) apply(other MediaPatch) {

	if other.Source.IsSet() {
		p.Source = other.Source
		delete(p.expressions, media.FieldSource)
	}

	if other.SourceURI.IsSet() {
		p.SourceURI = other.SourceURI
		delete(p.expressions, media.FieldSourceURI)
	}

	if other.Text.IsSet() {
		p.Text = other.Text
		delete(p.expressions, media.FieldText)
	}

	for column, render := range other.expressions {
		p.setExpr(column, render)
	}
	for edge, clear := range other.clearedEdges {
		if clear {
			if p.clearedEdges == nil {
				p.clearedEdges = make(map[string]bool)
			}
			p.clearedEdges[edge] = true
		}
	}
}
