// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package entv2

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
	time2 "time"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/entity"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/pet"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MixedString holds the value of the "mixed_string" field.
	MixedString string `json:"mixed_string,omitempty"`
	// MixedEnum holds the value of the "mixed_enum" field.
	MixedEnum user.MixedEnumValue `json:"mixed_enum,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Nickname holds the value of the "nickname" field.
	Nickname string `json:"nickname,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// Buffer holds the value of the "buffer" field.
	Buffer []byte `json:"buffer,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// NewName holds the value of the "new_name" field.
	NewName string `json:"new_name,omitempty"`
	// NewToken holds the value of the "new_token" field.
	NewToken string `json:"new_token,omitempty"`
	// Blob holds the value of the "blob" field.
	Blob []byte `json:"blob,omitempty"`
	// State holds the value of the "state" field.
	State user.StateValue `json:"state,omitempty"`
	// Status holds the value of the "status" field.
	Status user.StatusValue `json:"status,omitempty"`
	// Workplace holds the value of the "workplace" field.
	Workplace string `json:"workplace,omitempty"`
	// Roles holds the value of the "roles" field.
	Roles []string `json:"roles,omitempty"`
	// DefaultExpr holds the value of the "default_expr" field.
	DefaultExpr string `json:"default_expr,omitempty"`
	// DefaultExprs holds the value of the "default_exprs" field.
	DefaultExprs string `json:"default_exprs,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time2.Time `json:"created_at,omitempty"`
	// DropOptional holds the value of the "drop_optional" field.
	DropOptional string `json:"drop_optional,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges       UserEdges `json:"edges"`
	blog_admins *int
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Car holds the value of the car edge.
	Car []*Car `json:"car,omitempty"`
	// Pets holds the value of the pets edge.
	Pets *Pet `json:"pets,omitempty"`
	// Friends holds the value of the friends edge.
	Friends []*User `json:"friends,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	counts      map[string]int
}

func (e UserEdges) Loaded[N, K any](edge ent.RelationOf[entity.User, N, K]) bool {
	switch edge.Ref().Name {
	case "car":
		return e.loadedTypes[0]
	case "pets":
		return e.loadedTypes[1]
	case "friends":
		return e.loadedTypes[2]

	default:
		return false
	}
}

func (e *UserEdges) SetLoaded[N, K any](edge ent.RelationOf[entity.User, N, K], loaded bool) {
	switch edge.Ref().Name {
	case "car":
		e.loadedTypes[0] = loaded
	case "pets":
		e.loadedTypes[1] = loaded
	case "friends":
		e.loadedTypes[2] = loaded

	}
}

func (e UserEdges) Count[N, K any](edge ent.Relation[entity.User, N, K]) (int, bool) {
	count, loaded := e.counts[edge.Ref().Name]
	return count, loaded
}

// CarOrErr returns the Car value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CarOrErr() ([]*Car, error) {
	if e.loadedTypes[0] {
		return e.Car, nil
	}
	return nil, &NotLoadedError{edge: "car"}
}

// PetsOrErr returns the Pets value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) PetsOrErr() (*Pet, error) {
	if e.Pets != nil {
		return e.Pets, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: pet.Label}
	}
	return nil, &NotLoadedError{edge: "pets"}
}

// FriendsOrErr returns the Friends value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FriendsOrErr() ([]*User, error) {
	if e.loadedTypes[2] {
		return e.Friends, nil
	}
	return nil, &NotLoadedError{edge: "friends"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldBuffer, user.FieldBlob:
			values[i] = new(*[]byte)
		case user.FieldActive:
			values[i] = new(*bool)
		case user.FieldID, user.FieldAge:
			values[i] = new(*int)
		case user.FieldMixedString, user.FieldName, user.FieldDescription, user.FieldNickname, user.FieldPhone, user.FieldTitle, user.FieldNewName, user.FieldNewToken, user.FieldWorkplace, user.FieldDefaultExpr, user.FieldDefaultExprs, user.FieldDropOptional:
			values[i] = new(*string)
		case user.FieldCreatedAt:
			values[i] = new(*time2.Time)
		case user.FieldMixedEnum:
			values[i] = new(*user.MixedEnumValue)
		case user.FieldState:
			values[i] = new(*user.StateValue)
		case user.FieldStatus:
			values[i] = new(*user.StatusValue)
		case user.FieldRoles:
			values[i] = new([]byte)
		case user.ForeignKeys[0]: // blog_admins
			values[i] = new(*int)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil && *value != nil {
				_m.ID = **value
			}
		case user.FieldMixedString:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field mixed_string", values[i])
			} else if value != nil && *value != nil {
				_m.MixedString = **value
			}
		case user.FieldMixedEnum:

			if value, ok := values[i].(**user.MixedEnumValue); !ok {
				return fmt.Errorf("unexpected type %T for field mixed_enum", values[i])
			} else if value != nil && *value != nil {
				_m.MixedEnum = **value
			}
		case user.FieldActive:

			if value, ok := values[i].(**bool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value != nil && *value != nil {
				_m.Active = **value
			}
		case user.FieldAge:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value != nil && *value != nil {
				_m.Age = **value
			}
		case user.FieldName:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value != nil && *value != nil {
				_m.Name = **value
			}
		case user.FieldDescription:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value != nil && *value != nil {
				_m.Description = **value
			}
		case user.FieldNickname:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field nickname", values[i])
			} else if value != nil && *value != nil {
				_m.Nickname = **value
			}
		case user.FieldPhone:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value != nil && *value != nil {
				_m.Phone = **value
			}
		case user.FieldBuffer:

			if value, ok := values[i].(**[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field buffer", values[i])
			} else if value != nil && *value != nil {
				_m.Buffer = **value
			}
		case user.FieldTitle:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value != nil && *value != nil {
				_m.Title = **value
			}
		case user.FieldNewName:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field new_name", values[i])
			} else if value != nil && *value != nil {
				_m.NewName = **value
			}
		case user.FieldNewToken:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field new_token", values[i])
			} else if value != nil && *value != nil {
				_m.NewToken = **value
			}
		case user.FieldBlob:

			if value, ok := values[i].(**[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field blob", values[i])
			} else if value != nil && *value != nil {
				_m.Blob = **value
			}
		case user.FieldState:

			if value, ok := values[i].(**user.StateValue); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value != nil && *value != nil {
				_m.State = **value
			}
		case user.FieldStatus:

			if value, ok := values[i].(**user.StatusValue); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value != nil && *value != nil {
				_m.Status = **value
			}
		case user.FieldWorkplace:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field workplace", values[i])
			} else if value != nil && *value != nil {
				_m.Workplace = **value
			}
		case user.FieldRoles:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field roles", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Roles); err != nil {
					return fmt.Errorf("unmarshal field roles: %w", err)
				}
			}
		case user.FieldDefaultExpr:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field default_expr", values[i])
			} else if value != nil && *value != nil {
				_m.DefaultExpr = **value
			}
		case user.FieldDefaultExprs:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field default_exprs", values[i])
			} else if value != nil && *value != nil {
				_m.DefaultExprs = **value
			}
		case user.FieldCreatedAt:

			if value, ok := values[i].(**time2.Time); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value != nil && *value != nil {
				_m.CreatedAt = **value
			}
		case user.FieldDropOptional:

			if value, ok := values[i].(**string); !ok {
				return fmt.Errorf("unexpected type %T for field drop_optional", values[i])
			} else if value != nil && *value != nil {
				_m.DropOptional = **value
			}
		case user.ForeignKeys[0]:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field blog_admins", values[i])
			} else if value != nil && *value != nil {
				_m.blog_admins = *value
			}
		}
	}
	return nil
}

// QueryCar queries the "car" edge of the User entity.
func (_m *User) QueryCar() *CarQuery {
	return NewUserClient(_m.config).QueryCar(_m)
}

// QueryPets queries the "pets" edge of the User entity.
func (_m *User) QueryPets() *PetQuery {
	return NewUserClient(_m.config).QueryPets(_m)
}

// QueryFriends queries the "friends" edge of the User entity.
func (_m *User) QueryFriends() *UserQuery {
	return NewUserClient(_m.config).QueryFriends(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("entv2: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("mixed_string=")
	builder.WriteString(_m.MixedString)
	builder.WriteString(", ")
	builder.WriteString("mixed_enum=")
	builder.WriteString(fmt.Sprintf("%v", _m.MixedEnum))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("age=")
	builder.WriteString(fmt.Sprintf("%v", _m.Age))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("nickname=")
	builder.WriteString(_m.Nickname)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("buffer=")
	builder.WriteString(fmt.Sprintf("%v", _m.Buffer))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("new_name=")
	builder.WriteString(_m.NewName)
	builder.WriteString(", ")
	builder.WriteString("new_token=")
	builder.WriteString(_m.NewToken)
	builder.WriteString(", ")
	builder.WriteString("blob=")
	builder.WriteString(fmt.Sprintf("%v", _m.Blob))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("workplace=")
	builder.WriteString(_m.Workplace)
	builder.WriteString(", ")
	builder.WriteString("roles=")
	builder.WriteString(fmt.Sprintf("%v", _m.Roles))
	builder.WriteString(", ")
	builder.WriteString("default_expr=")
	builder.WriteString(_m.DefaultExpr)
	builder.WriteString(", ")
	builder.WriteString("default_exprs=")
	builder.WriteString(_m.DefaultExprs)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("drop_optional=")
	builder.WriteString(_m.DropOptional)
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
