// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package entv2

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/car"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/entity"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/pet"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/user"
	"github.com/neko-sc/ent/schema/field"
)

type UserCreate struct {
	config
	mutation    *UserMutation
	err         error
	fromBuilder bool
	present     map[string]struct{}

	conflict []sql.ConflictOption
}

func (b *UserCreate) Set[T any](column ent.ColumnOf[entity.User, T], value T) *UserCreate {
	if b.err == nil {
		b.err = b.mutation.insert.set(column.Ref().Name, value)
	}
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b
}
func (b *UserCreate) SetOptional[T any](column ent.ColumnOf[entity.User, T], value ent.Option[T]) *UserCreate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.insert.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *UserCreate) SetExpr[T any](column ent.ColumnOf[entity.User, T], value ent.Expr[T]) *UserCreate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case user.FieldID:

	case user.FieldMixedString:

	case user.FieldMixedEnum:

	case user.FieldActive:

	case user.FieldAge:

	case user.FieldName:

	case user.FieldDescription:

	case user.FieldNickname:

	case user.FieldPhone:

	case user.FieldBuffer:

	case user.FieldTitle:

	case user.FieldNewName:

	case user.FieldNewToken:

	case user.FieldBlob:

	case user.FieldState:

	case user.FieldStatus:

	case user.FieldWorkplace:

	case user.FieldRoles:

	case user.FieldDefaultExpr:

	case user.FieldDefaultExprs:

	case user.FieldCreatedAt:

	case user.FieldDropOptional:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of User is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.insert.setExpr(column.Ref().Name, value.Render)
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b

}
func (b *UserCreate) SetEdge[N, K any](edge ent.UniqueRelation[entity.User, N, K], id K) *UserCreate {
	if b.err == nil {
		b.err = b.mutation.insert.setEdge(edge.Ref().Name, id)
	}

	switch edge.Ref().Name {

	}

	return b
}
func (b *UserCreate) AddIDs[N, K any](edge ent.Relation[entity.User, N, K], ids ...K) *UserCreate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.insert.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *UserCreate) Mutation() *UserMutation { return b.mutation }

func (b *UserCreate) Insert() *UserInsert { return b.mutation.insert }

func (b *UserCreate) Save(ctx context.Context) (*User, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *UserCreate) SaveX(ctx context.Context) *User {
	node, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

func (b *UserCreate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *UserCreate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *UserCreate) defaults() error {

	if b.mutation.insert.MixedString.IsUnset() && b.mutation.insert.expressions[user.FieldMixedString] == nil {

		b.mutation.insert.MixedString = ent.Some(user.DefaultMixedString)
	}

	if b.mutation.insert.MixedEnum.IsUnset() && b.mutation.insert.expressions[user.FieldMixedEnum] == nil {

		b.mutation.insert.MixedEnum = ent.Some(user.DefaultMixedEnum)
	}

	if b.mutation.insert.Active.IsUnset() && b.mutation.insert.expressions[user.FieldActive] == nil {

		b.mutation.insert.Active = ent.Some(user.DefaultActive)
	}

	if b.mutation.insert.Phone.IsUnset() && b.mutation.insert.expressions[user.FieldPhone] == nil {

		b.mutation.insert.Phone = ent.Some(user.DefaultPhone)
	}

	if b.mutation.insert.Buffer.IsUnset() && b.mutation.insert.expressions[user.FieldBuffer] == nil {
		if user.DefaultBuffer == nil {
			return fmt.Errorf("ent: uninitialized user.DefaultBuffer")
		}
		b.mutation.insert.Buffer = ent.Some(user.DefaultBuffer())
	}

	if b.mutation.insert.Title.IsUnset() && b.mutation.insert.expressions[user.FieldTitle] == nil {

		b.mutation.insert.Title = ent.Some(user.DefaultTitle)
	}

	if b.mutation.insert.NewToken.IsUnset() && b.mutation.insert.expressions[user.FieldNewToken] == nil {
		if user.DefaultNewToken == nil {
			return fmt.Errorf("ent: uninitialized user.DefaultNewToken")
		}
		b.mutation.insert.NewToken = ent.Some(user.DefaultNewToken())
	}

	if b.mutation.insert.State.IsUnset() && b.mutation.insert.expressions[user.FieldState] == nil {

		b.mutation.insert.State = ent.Some(user.DefaultState)
	}

	if b.mutation.insert.CreatedAt.IsUnset() && b.mutation.insert.expressions[user.FieldCreatedAt] == nil {
		if user.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized user.DefaultCreatedAt")
		}
		b.mutation.insert.CreatedAt = ent.Some(user.DefaultCreatedAt())
	}

	if b.mutation.insert.DropOptional.IsUnset() && b.mutation.insert.expressions[user.FieldDropOptional] == nil {
		if user.DefaultDropOptional == nil {
			return fmt.Errorf("ent: uninitialized user.DefaultDropOptional")
		}
		b.mutation.insert.DropOptional = ent.Some(user.DefaultDropOptional())
	}

	return nil
}

func (b *UserCreate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.insert.ID.IsNull() {
		return &ValidationError{Name: "id", err: errors.New(`ent: field "User.id" is not nullable`)}
	}

	if b.mutation.insert.MixedString.IsNull() {
		return &ValidationError{Name: "mixed_string", err: errors.New(`ent: field "User.mixed_string" is not nullable`)}
	}

	if b.mutation.insert.MixedEnum.IsNull() {
		return &ValidationError{Name: "mixed_enum", err: errors.New(`ent: field "User.mixed_enum" is not nullable`)}
	}

	if b.mutation.insert.expressions[user.FieldMixedEnum] == nil {
		if v, ok := b.mutation.insert.MixedEnum.Get(); ok {

			if err := user.MixedEnumValidator(v); err != nil {
				return &ValidationError{Name: "mixed_enum", err: fmt.Errorf(`ent: validator failed for field "User.mixed_enum": %w`, err)}
			}

		}
	}

	if b.mutation.insert.Active.IsNull() {
		return &ValidationError{Name: "active", err: errors.New(`ent: field "User.active" is not nullable`)}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[user.FieldAge]; b.fromBuilder && !present {
			return &ValidationError{Name: "age", err: errors.New(`ent: missing required field "User.age"`)}
		}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[user.FieldName]; b.fromBuilder && !present {
			return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "User.name"`)}
		}
	}

	switch b.driver.Dialect() {
	case dialect.Postgres, dialect.SQLite:
		if _, present := b.present[user.FieldNickname]; b.fromBuilder && !present {
			return &ValidationError{Name: "nickname", err: errors.New(`ent: missing required field "User.nickname"`)}
		}
	}

	if b.mutation.insert.expressions[user.FieldNickname] == nil {
		v := b.mutation.insert.Nickname

		if err := user.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "User.nickname": %w`, err)}
		}

	}

	if b.mutation.insert.Phone.IsNull() {
		return &ValidationError{Name: "phone", err: errors.New(`ent: field "User.phone" is not nullable`)}
	}

	if b.mutation.insert.Title.IsNull() {
		return &ValidationError{Name: "title", err: errors.New(`ent: field "User.title" is not nullable`)}
	}

	if b.mutation.insert.NewToken.IsNull() {
		return &ValidationError{Name: "new_token", err: errors.New(`ent: field "User.new_token" is not nullable`)}
	}

	if b.mutation.insert.expressions[user.FieldBlob] == nil {
		if v, ok := b.mutation.insert.Blob.Get(); ok {

			if err := user.BlobValidator(v); err != nil {
				return &ValidationError{Name: "blob", err: fmt.Errorf(`ent: validator failed for field "User.blob": %w`, err)}
			}

		}
	}

	if b.mutation.insert.expressions[user.FieldState] == nil {
		if v, ok := b.mutation.insert.State.Get(); ok {

			if err := user.StateValidator(v); err != nil {
				return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "User.state": %w`, err)}
			}

		}
	}

	if b.mutation.insert.expressions[user.FieldStatus] == nil {
		if v, ok := b.mutation.insert.Status.Get(); ok {

			if err := user.StatusValidator(v); err != nil {
				return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "User.status": %w`, err)}
			}

		}
	}

	if b.mutation.insert.CreatedAt.IsNull() {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: field "User.created_at" is not nullable`)}
	}

	if b.mutation.insert.DropOptional.IsNull() {
		return &ValidationError{Name: "drop_optional", err: errors.New(`ent: field "User.drop_optional" is not nullable`)}
	}

	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	node, spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	_c.mutation.id = &node.ID
	return node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec, error) {
	_node := &User{config: _c.config}
	_spec := sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))

	_spec.OnConflict = _c.conflict

	if value, ok := _c.mutation.insert.ID.Get(); ok {
		_spec.ID.Value = value
	}

	if value, ok := _c.mutation.insert.MixedString.Get(); ok {
		_spec.SetField(user.FieldMixedString, field.TypeString, value)
	}
	if _c.mutation.insert.MixedString.IsNull() {
		_spec.SetField(user.FieldMixedString, field.TypeString, nil)
	}

	if value, ok := _c.mutation.insert.MixedEnum.Get(); ok {
		_spec.SetField(user.FieldMixedEnum, field.TypeEnum, value)
	}
	if _c.mutation.insert.MixedEnum.IsNull() {
		_spec.SetField(user.FieldMixedEnum, field.TypeEnum, nil)
	}

	if value, ok := _c.mutation.insert.Active.Get(); ok {
		_spec.SetField(user.FieldActive, field.TypeBool, value)
	}
	if _c.mutation.insert.Active.IsNull() {
		_spec.SetField(user.FieldActive, field.TypeBool, nil)
	}

	if _, present := _c.present[user.FieldAge]; !_c.fromBuilder || present {
		value := _c.mutation.insert.Age
		_spec.SetField(user.FieldAge, field.TypeInt, value)
	}

	if _, present := _c.present[user.FieldName]; !_c.fromBuilder || present {
		value := _c.mutation.insert.Name
		_spec.SetField(user.FieldName, field.TypeString, value)
	}

	if value, ok := _c.mutation.insert.Description.Get(); ok {
		_spec.SetField(user.FieldDescription, field.TypeString, value)
	}
	if _c.mutation.insert.Description.IsNull() {
		_spec.SetField(user.FieldDescription, field.TypeString, nil)
	}

	if _, present := _c.present[user.FieldNickname]; !_c.fromBuilder || present {
		value := _c.mutation.insert.Nickname
		_spec.SetField(user.FieldNickname, field.TypeString, value)
	}

	if value, ok := _c.mutation.insert.Phone.Get(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if _c.mutation.insert.Phone.IsNull() {
		_spec.SetField(user.FieldPhone, field.TypeString, nil)
	}

	if value, ok := _c.mutation.insert.Buffer.Get(); ok {
		_spec.SetField(user.FieldBuffer, field.TypeBytes, value)
	}
	if _c.mutation.insert.Buffer.IsNull() {
		_spec.SetField(user.FieldBuffer, field.TypeBytes, nil)
	}

	if value, ok := _c.mutation.insert.Title.Get(); ok {
		_spec.SetField(user.FieldTitle, field.TypeString, value)
	}
	if _c.mutation.insert.Title.IsNull() {
		_spec.SetField(user.FieldTitle, field.TypeString, nil)
	}

	if value, ok := _c.mutation.insert.NewName.Get(); ok {
		_spec.SetField(user.FieldNewName, field.TypeString, value)
	}
	if _c.mutation.insert.NewName.IsNull() {
		_spec.SetField(user.FieldNewName, field.TypeString, nil)
	}

	if value, ok := _c.mutation.insert.NewToken.Get(); ok {
		_spec.SetField(user.FieldNewToken, field.TypeString, value)
	}
	if _c.mutation.insert.NewToken.IsNull() {
		_spec.SetField(user.FieldNewToken, field.TypeString, nil)
	}

	if value, ok := _c.mutation.insert.Blob.Get(); ok {
		_spec.SetField(user.FieldBlob, field.TypeBytes, value)
	}
	if _c.mutation.insert.Blob.IsNull() {
		_spec.SetField(user.FieldBlob, field.TypeBytes, nil)
	}

	if value, ok := _c.mutation.insert.State.Get(); ok {
		_spec.SetField(user.FieldState, field.TypeEnum, value)
	}
	if _c.mutation.insert.State.IsNull() {
		_spec.SetField(user.FieldState, field.TypeEnum, nil)
	}

	if value, ok := _c.mutation.insert.Status.Get(); ok {
		_spec.SetField(user.FieldStatus, field.TypeEnum, value)
	}
	if _c.mutation.insert.Status.IsNull() {
		_spec.SetField(user.FieldStatus, field.TypeEnum, nil)
	}

	if value, ok := _c.mutation.insert.Workplace.Get(); ok {
		_spec.SetField(user.FieldWorkplace, field.TypeString, value)
	}
	if _c.mutation.insert.Workplace.IsNull() {
		_spec.SetField(user.FieldWorkplace, field.TypeString, nil)
	}

	if value, ok := _c.mutation.insert.Roles.Get(); ok {
		_spec.SetField(user.FieldRoles, field.TypeJSON, value)
	}
	if _c.mutation.insert.Roles.IsNull() {
		_spec.SetField(user.FieldRoles, field.TypeJSON, nil)
	}

	if value, ok := _c.mutation.insert.DefaultExpr.Get(); ok {
		_spec.SetField(user.FieldDefaultExpr, field.TypeString, value)
	}
	if _c.mutation.insert.DefaultExpr.IsNull() {
		_spec.SetField(user.FieldDefaultExpr, field.TypeString, nil)
	}

	if value, ok := _c.mutation.insert.DefaultExprs.Get(); ok {
		_spec.SetField(user.FieldDefaultExprs, field.TypeString, value)
	}
	if _c.mutation.insert.DefaultExprs.IsNull() {
		_spec.SetField(user.FieldDefaultExprs, field.TypeString, nil)
	}

	if value, ok := _c.mutation.insert.CreatedAt.Get(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if _c.mutation.insert.CreatedAt.IsNull() {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, nil)
	}

	if value, ok := _c.mutation.insert.DropOptional.Get(); ok {
		_spec.SetField(user.FieldDropOptional, field.TypeString, value)
	}
	if _c.mutation.insert.DropOptional.IsNull() {
		_spec.SetField(user.FieldDropOptional, field.TypeString, nil)
	}

	_spec.Expressions = _c.mutation.insert.expressions

	if nodes := _c.mutation.insert.carIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CarTable,
			Columns: []string{user.CarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(car.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	if nodes := _c.mutation.insert.petsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.PetsTable,
			Columns: []string{user.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	if nodes := _c.mutation.insert.friendsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FriendsTable,
			Columns: user.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}

	_spec.Returning = &sqlgraph.Returning{Columns: user.Columns, Scan: func(rows dialect.Rows) error {
		values, err := _node.scanValues(user.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(user.Columns, values); err != nil {
			return err
		}

		_spec.ID.Value = _node.ID

		return nil
	}}
	return _node, _spec, nil
}

type UserUpsertOne struct{ create *UserCreate }

func (b *UserCreate) OnConflict(columns ...ent.EntityColumn[entity.User]) *UserUpsertOne {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *UserCreate) OnConflictConstraint(name string) *UserUpsertOne {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *UserCreate) OnConflictOptions(options ...sql.ConflictOption) *UserUpsertOne {
	b.conflict = options
	return &UserUpsertOne{create: b}
}

func (u *UserUpsertOne) DoNothing() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *UserUpsertOne) DoSelect() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *UserUpsertOne) Ignore() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *UserUpsertOne) DoUpdate(set func(*UserUpsert)) *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&UserUpsert{UpdateSet: update}) }))
	return u
}

func (u *UserUpsertOne) UpdateNewValues() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case user.FieldID:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *UserUpsertOne) Where(predicates ...ent.Predicate[entity.User]) *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(user.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *UserUpsertOne) UpdateWhere(predicates ...ent.Predicate[entity.User]) *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(user.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *UserUpsertOne) Save(ctx context.Context) (*User, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for UserCreate.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *UserUpsertOne) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *UserUpsertOne) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (u *UserUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

func (u *UserUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

type UserUpsert struct{ *sql.UpdateSet }

func (u *UserUpsert) Set[T any](column ent.ColumnOf[entity.User, T], value T) *UserUpsert {
	switch column.Ref().Name {

	case user.FieldMixedString:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldMixedEnum:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldActive:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldAge:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldName:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldDescription:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldNickname:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldPhone:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldBuffer:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldTitle:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldNewName:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldNewToken:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldBlob:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldState:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldStatus:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldWorkplace:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldRoles:

		encoded, err := json.Marshal(value)
		if err != nil {
			u.UpdateSet.AddError(err)
			return u
		}
		u.UpdateSet.Set(column.Ref().Name, json.RawMessage(encoded))

	case user.FieldDefaultExpr:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldDefaultExprs:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldCreatedAt:
		u.UpdateSet.Set(column.Ref().Name, value)

	case user.FieldDropOptional:
		u.UpdateSet.Set(column.Ref().Name, value)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of User is not settable", column.Ref().Name)})
	}
	return u
}

func (u *UserUpsert) SetExpr[T any](column ent.ColumnOf[entity.User, T], value ent.Expr[T]) *UserUpsert {
	switch column.Ref().Name {

	case user.FieldMixedString:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldMixedEnum:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldActive:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldAge:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldName:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldDescription:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldNickname:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldPhone:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldBuffer:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldTitle:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldNewName:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldNewToken:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldBlob:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldState:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldStatus:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldWorkplace:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldRoles:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldDefaultExpr:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldDefaultExprs:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldCreatedAt:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	case user.FieldDropOptional:
		u.UpdateSet.Set(column.Ref().Name, sql.ExprFunc(value.Render))

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of User is not settable", column.Ref().Name)})
	}
	return u
}

func (u *UserUpsert) UpdateNewValue[T any](column ent.ColumnOf[entity.User, T]) *UserUpsert {
	switch column.Ref().Name {

	case user.FieldMixedString:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldMixedEnum:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldActive:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldAge:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldName:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldDescription:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldNickname:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldPhone:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldBuffer:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldTitle:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldNewName:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldNewToken:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldBlob:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldState:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldStatus:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldWorkplace:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldRoles:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldDefaultExpr:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldDefaultExprs:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldCreatedAt:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	case user.FieldDropOptional:
		u.UpdateSet.SetExcluded(column.Ref().Name)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of User is not settable", column.Ref().Name)})
	}
	return u
}

func (u *UserUpsert) Add[T ent.Number](column ent.ColumnOf[entity.User, T], delta T) *UserUpsert {
	switch column.Ref().Name {

	case user.FieldAge:
		u.UpdateSet.Add(column.Ref().Name, delta)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of User does not support addition", column.Ref().Name)})
	}
	return u
}

func (u *UserUpsert) Clear[T any](column ent.ColumnOf[entity.User, T]) *UserUpsert {
	switch column.Ref().Name {

	case user.FieldDescription:
		u.UpdateSet.SetNull(column.Ref().Name)

	case user.FieldBuffer:
		u.UpdateSet.SetNull(column.Ref().Name)

	case user.FieldNewName:
		u.UpdateSet.SetNull(column.Ref().Name)

	case user.FieldBlob:
		u.UpdateSet.SetNull(column.Ref().Name)

	case user.FieldState:
		u.UpdateSet.SetNull(column.Ref().Name)

	case user.FieldStatus:
		u.UpdateSet.SetNull(column.Ref().Name)

	case user.FieldWorkplace:
		u.UpdateSet.SetNull(column.Ref().Name)

	case user.FieldRoles:
		u.UpdateSet.SetNull(column.Ref().Name)

	case user.FieldDefaultExpr:
		u.UpdateSet.SetNull(column.Ref().Name)

	case user.FieldDefaultExprs:
		u.UpdateSet.SetNull(column.Ref().Name)

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of User is not nullable", column.Ref().Name)})
	}
	return u
}

type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate

	conflict []sql.ConflictOption
}

func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	nodes := make([]*User, len(_c.builders))
	specs := make([]*sqlgraph.CreateSpec, len(nodes))
	for index, builder := range _c.builders {
		if builder.err != nil {
			return nil, builder.err
		}
		if err := builder.defaults(); err != nil {
			return nil, err
		}
		if err := builder.check(); err != nil {
			return nil, err
		}
		var err error
		nodes[index], specs[index], err = builder.createSpec()
		if err != nil {
			return nil, err
		}
	}
	if len(specs) == 0 {
		return nodes, nil
	}
	spec := &sqlgraph.BatchCreateSpec{Nodes: specs}

	spec.OnConflict = _c.conflict

	if err := sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	result := nodes[:0]
	for index, builder := range _c.builders {
		if specs[index].Skipped {
			continue
		}
		builder.mutation.id = &nodes[index].ID
		result = append(result, nodes[index])
	}
	return result, nil
}

func (b *UserCreateBulk) SaveX(ctx context.Context) []*User {
	nodes, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

func (b *UserCreateBulk) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *UserCreateBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

type UserUpsertBulk struct{ create *UserCreateBulk }

func (b *UserCreateBulk) OnConflict(columns ...ent.EntityColumn[entity.User]) *UserUpsertBulk {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *UserCreateBulk) OnConflictConstraint(name string) *UserUpsertBulk {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *UserCreateBulk) OnConflictOptions(options ...sql.ConflictOption) *UserUpsertBulk {
	b.conflict = options
	return &UserUpsertBulk{create: b}
}

func (u *UserUpsertBulk) DoNothing() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *UserUpsertBulk) DoSelect() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *UserUpsertBulk) Ignore() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *UserUpsertBulk) DoUpdate(set func(*UserUpsert)) *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&UserUpsert{UpdateSet: update}) }))
	return u
}

func (u *UserUpsertBulk) UpdateNewValues() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case user.FieldID:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *UserUpsertBulk) Where(predicates ...ent.Predicate[entity.User]) *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(user.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *UserUpsertBulk) UpdateWhere(predicates ...ent.Predicate[entity.User]) *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(user.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *UserUpsertBulk) Save(ctx context.Context) ([]*User, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for UserCreateBulk.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *UserUpsertBulk) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *UserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}
