// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package entv2

import (
	"context"
	"errors"
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/entity"
	"github.com/neko-sc/ent/entc/integration/migrate/entv2/zoo"
	"github.com/neko-sc/ent/schema/field"
)

type ZooCreate struct {
	config
	mutation    *ZooMutation
	err         error
	fromBuilder bool
	present     map[string]struct{}

	conflict []sql.ConflictOption
}

func (b *ZooCreate) Set[T any](column ent.ColumnOf[entity.Zoo, T], value T) *ZooCreate {
	if b.err == nil {
		b.err = b.mutation.insert.set(column.Ref().Name, value)
	}
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b
}
func (b *ZooCreate) SetOptional[T any](column ent.ColumnOf[entity.Zoo, T], value ent.Option[T]) *ZooCreate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.insert.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *ZooCreate) SetExpr[T any](column ent.ColumnOf[entity.Zoo, T], value ent.Expr[T]) *ZooCreate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case zoo.FieldID:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Zoo is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.insert.setExpr(column.Ref().Name, value.Render)
	if b.present == nil {
		b.present = make(map[string]struct{})
	}
	b.present[column.Ref().Name] = struct{}{}
	return b

}
func (b *ZooCreate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Zoo, N, K], id K) *ZooCreate {
	if b.err == nil {
		b.err = b.mutation.insert.setEdge(edge.Ref().Name, id)
	}

	switch edge.Ref().Name {

	}

	return b
}
func (b *ZooCreate) AddIDs[N, K any](edge ent.Relation[entity.Zoo, N, K], ids ...K) *ZooCreate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.insert.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *ZooCreate) Mutation() *ZooMutation { return b.mutation }

func (b *ZooCreate) Insert() *ZooInsert { return b.mutation.insert }

func (b *ZooCreate) Save(ctx context.Context) (*Zoo, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *ZooCreate) SaveX(ctx context.Context) *Zoo {
	node, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

func (b *ZooCreate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *ZooCreate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *ZooCreate) defaults() error {

	return nil
}

func (b *ZooCreate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.insert.ID.IsNull() {
		return &ValidationError{Name: "id", err: errors.New(`ent: field "Zoo.id" is not nullable`)}
	}

	return nil
}

func (_c *ZooCreate) sqlSave(ctx context.Context) (*Zoo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	node, spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	_c.mutation.id = &node.ID
	return node, nil
}

func (_c *ZooCreate) createSpec() (*Zoo, *sqlgraph.CreateSpec, error) {
	_node := &Zoo{config: _c.config}
	_spec := sqlgraph.NewCreateSpec(zoo.Table, sqlgraph.NewFieldSpec(zoo.FieldID, field.TypeInt))

	_spec.OnConflict = _c.conflict

	if value, ok := _c.mutation.insert.ID.Get(); ok {
		_spec.ID.Value = value
	}

	_spec.Expressions = _c.mutation.insert.expressions

	_spec.Returning = &sqlgraph.Returning{Columns: zoo.Columns, Scan: func(rows dialect.Rows) error {
		values, err := _node.scanValues(zoo.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(zoo.Columns, values); err != nil {
			return err
		}

		_spec.ID.Value = _node.ID

		return nil
	}}
	return _node, _spec, nil
}

type ZooUpsertOne struct{ create *ZooCreate }

func (b *ZooCreate) OnConflict(columns ...ent.EntityColumn[entity.Zoo]) *ZooUpsertOne {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *ZooCreate) OnConflictConstraint(name string) *ZooUpsertOne {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *ZooCreate) OnConflictOptions(options ...sql.ConflictOption) *ZooUpsertOne {
	b.conflict = options
	return &ZooUpsertOne{create: b}
}

func (u *ZooUpsertOne) DoNothing() *ZooUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *ZooUpsertOne) DoSelect() *ZooUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *ZooUpsertOne) Ignore() *ZooUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *ZooUpsertOne) DoUpdate(set func(*ZooUpsert)) *ZooUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&ZooUpsert{UpdateSet: update}) }))
	return u
}

func (u *ZooUpsertOne) UpdateNewValues() *ZooUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case zoo.FieldID:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *ZooUpsertOne) Where(predicates ...ent.Predicate[entity.Zoo]) *ZooUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(zoo.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *ZooUpsertOne) UpdateWhere(predicates ...ent.Predicate[entity.Zoo]) *ZooUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(zoo.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *ZooUpsertOne) Save(ctx context.Context) (*Zoo, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for ZooCreate.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *ZooUpsertOne) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *ZooUpsertOne) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (u *ZooUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

func (u *ZooUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

type ZooUpsert struct{ *sql.UpdateSet }

func (u *ZooUpsert) Set[T any](column ent.ColumnOf[entity.Zoo, T], value T) *ZooUpsert {
	switch column.Ref().Name {

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Zoo is not settable", column.Ref().Name)})
	}
	return u
}

func (u *ZooUpsert) SetExpr[T any](column ent.ColumnOf[entity.Zoo, T], value ent.Expr[T]) *ZooUpsert {
	switch column.Ref().Name {

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Zoo is not settable", column.Ref().Name)})
	}
	return u
}

func (u *ZooUpsert) UpdateNewValue[T any](column ent.ColumnOf[entity.Zoo, T]) *ZooUpsert {
	switch column.Ref().Name {

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Zoo is not settable", column.Ref().Name)})
	}
	return u
}

func (u *ZooUpsert) Add[T ent.Number](column ent.ColumnOf[entity.Zoo, T], delta T) *ZooUpsert {
	switch column.Ref().Name {

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Zoo does not support addition", column.Ref().Name)})
	}
	return u
}

func (u *ZooUpsert) Clear[T any](column ent.ColumnOf[entity.Zoo, T]) *ZooUpsert {
	switch column.Ref().Name {

	default:
		u.UpdateSet.AddError(&ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Zoo is not nullable", column.Ref().Name)})
	}
	return u
}

type ZooCreateBulk struct {
	config
	err      error
	builders []*ZooCreate

	conflict []sql.ConflictOption
}

func (_c *ZooCreateBulk) Save(ctx context.Context) ([]*Zoo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	nodes := make([]*Zoo, len(_c.builders))
	specs := make([]*sqlgraph.CreateSpec, len(nodes))
	for index, builder := range _c.builders {
		if builder.err != nil {
			return nil, builder.err
		}
		if err := builder.defaults(); err != nil {
			return nil, err
		}
		if err := builder.check(); err != nil {
			return nil, err
		}
		var err error
		nodes[index], specs[index], err = builder.createSpec()
		if err != nil {
			return nil, err
		}
	}
	if len(specs) == 0 {
		return nodes, nil
	}
	spec := &sqlgraph.BatchCreateSpec{Nodes: specs}

	spec.OnConflict = _c.conflict

	if err := sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		if errors.Is(err, dialect.ErrNoRows) {
			err = ErrConflict
		}
		return nil, err
	}
	result := nodes[:0]
	for index, builder := range _c.builders {
		if specs[index].Skipped {
			continue
		}
		builder.mutation.id = &nodes[index].ID
		result = append(result, nodes[index])
	}
	return result, nil
}

func (b *ZooCreateBulk) SaveX(ctx context.Context) []*Zoo {
	nodes, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

func (b *ZooCreateBulk) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *ZooCreateBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

type ZooUpsertBulk struct{ create *ZooCreateBulk }

func (b *ZooCreateBulk) OnConflict(columns ...ent.EntityColumn[entity.Zoo]) *ZooUpsertBulk {
	names := make([]string, len(columns))
	for index := range columns {
		names[index] = columns[index].Ref().Name
	}
	if len(names) == 0 {
		return b.OnConflictOptions()
	}
	return b.OnConflictOptions(sql.ConflictColumns(names...))
}

func (b *ZooCreateBulk) OnConflictConstraint(name string) *ZooUpsertBulk {
	return b.OnConflictOptions(sql.ConflictConstraint(name))
}

func (b *ZooCreateBulk) OnConflictOptions(options ...sql.ConflictOption) *ZooUpsertBulk {
	b.conflict = options
	return &ZooUpsertBulk{create: b}
}

func (u *ZooUpsertBulk) DoNothing() *ZooUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

func (u *ZooUpsertBulk) DoSelect() *ZooUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoSelect())
	return u
}

func (u *ZooUpsertBulk) Ignore() *ZooUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

func (u *ZooUpsertBulk) DoUpdate(set func(*ZooUpsert)) *ZooUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) { set(&ZooUpsert{UpdateSet: update}) }))
	return u
}

func (u *ZooUpsertBulk) UpdateNewValues() *ZooUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues(), sql.ResolveWith(func(update *sql.UpdateSet) {
		for _, column := range update.Columns() {
			switch column {
			case zoo.FieldID:
				update.SetIgnore(column)

			}
		}
	}))
	return u
}

func (u *ZooUpsertBulk) Where(predicates ...ent.Predicate[entity.Zoo]) *ZooUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ConflictWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(zoo.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *ZooUpsertBulk) UpdateWhere(predicates ...ent.Predicate[entity.Zoo]) *ZooUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.UpdateWhere(sql.P(func(renderer *sql.Builder) {
		selector := sql.Dialect(renderer.Dialect()).Select().From(sql.Table(zoo.Table))
		for _, predicate := range predicates {
			predicate(selector)
		}
		renderer.Join(selector.P())
	})))
	return u
}

func (u *ZooUpsertBulk) Save(ctx context.Context) ([]*Zoo, error) {
	if len(u.create.conflict) == 0 {
		return nil, errors.New("ent: missing options for ZooCreateBulk.OnConflict")
	}
	return u.create.Save(ctx)
}

func (u *ZooUpsertBulk) Exec(ctx context.Context) error {
	_, err := u.Save(ctx)
	if errors.Is(err, ErrConflict) {
		return nil
	}
	return err
}

func (u *ZooUpsertBulk) ExecX(ctx context.Context) {
	if err := u.Exec(ctx); err != nil {
		panic(err)
	}
}
