// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/examples/m2mbidi/ent/entity"
	"github.com/neko-sc/ent/examples/m2mbidi/ent/user"
	"github.com/neko-sc/ent/schema/field"
)

// UserDelete is the builder for deleting a User entity.
type UserDelete struct {
	config

	mutation  *UserMutation
	returning *sqlgraph.Returning
}

// Where appends a list predicates to the UserDelete builder.
func (_d *UserDelete) Where(predicates ...ent.Predicate[entity.User]) *UserDelete {
	_d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserDelete) Exec(ctx context.Context) (int, error) {
	return _d.sqlExec(ctx)
}

func (b *UserDelete) Returning(ctx context.Context) ([]*User, error) {
	nodes := make([]*User, 0)
	b.returning = &sqlgraph.Returning{Columns: user.Columns, Scan: func(rows dialect.Rows) error {
		_node := &User{config: b.config}
		values, err := _node.scanValues(user.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(user.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Exec(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _d.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_spec.Returning = _d.returning
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// UserDeleteOne is the builder for deleting a single User entity.
type UserDeleteOne struct {
	_d *UserDelete
}

// Where appends a list predicates to the UserDelete builder.
func (_d *UserDeleteOne) Where(predicates ...ent.Predicate[entity.User]) *UserDeleteOne {
	_d._d.mutation.Where(predicates...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{user.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
