// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/examples/migration/ent/card"
	"github.com/neko-sc/ent/examples/migration/ent/entity"
	"github.com/neko-sc/ent/examples/migration/ent/payment"
	"github.com/neko-sc/ent/schema/field"
)

type PaymentUpdate struct {
	config
	mutation  *PaymentMutation
	err       error
	returning *sqlgraph.Returning

	modifiers []func(*sql.UpdateBuilder)
}

func (b *PaymentUpdate) Set[T any](column ent.ColumnOf[entity.Payment, T], value T) *PaymentUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *PaymentUpdate) SetOptional[T any](column ent.ColumnOf[entity.Payment, T], value ent.Option[T]) *PaymentUpdate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *PaymentUpdate) SetExpr[T any](column ent.ColumnOf[entity.Payment, T], value ent.Expr[T]) *PaymentUpdate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case payment.FieldCardID:

	case payment.FieldAmount:

	case payment.FieldCurrency:

	case payment.FieldTime:

	case payment.FieldDescription:

	case payment.FieldStatus:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Payment is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *PaymentUpdate) SetEdge[N, K any](edge ent.UniqueRelation[entity.Payment, N, K], id K) *PaymentUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *PaymentUpdate) AddIDs[N, K any](edge ent.Relation[entity.Payment, N, K], ids ...K) *PaymentUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *PaymentUpdate) Mutation() *PaymentMutation { return b.mutation }

func (b *PaymentUpdate) Patch() *PaymentPatch                { return b.mutation.patch }
func (b *PaymentUpdate) Apply(p PaymentPatch) *PaymentUpdate { b.mutation.patch.apply(p); return b }
func (b *PaymentUpdate) Add[T ent.Number](column ent.ColumnOf[entity.Payment, T], delta T) *PaymentUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *PaymentUpdate) Append[T any](column ent.ColumnOf[entity.Payment, T], values T) *PaymentUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *PaymentUpdate) Clear[T any](column ent.ColumnOf[entity.Payment, T]) *PaymentUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *PaymentUpdate) RemoveIDs[N, K any](edge ent.Relation[entity.Payment, N, K], ids ...K) *PaymentUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *PaymentUpdate) ClearEdge[N, K any](edge ent.RelationOf[entity.Payment, N, K]) *PaymentUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *PaymentUpdate) Where(predicates ...ent.Predicate[entity.Payment]) *PaymentUpdate {
	b.mutation.Where(predicates...)
	return b
}

func (b *PaymentUpdate) Save(ctx context.Context) (int, error) {
	if b.err != nil {
		return 0, b.err
	}
	if err := b.defaults(); err != nil {
		return 0, err
	}
	return b.sqlSave(ctx)
}

func (b *PaymentUpdate) SaveX(ctx context.Context) int {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *PaymentUpdate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *PaymentUpdate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *PaymentUpdate) Returning(ctx context.Context) ([]*Payment, error) {
	nodes := make([]*Payment, 0)
	b.returning = &sqlgraph.Returning{Columns: payment.Columns, Scan: func(rows dialect.Rows) error {
		_node := &Payment{config: b.config}
		values, err := _node.scanValues(payment.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(payment.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Save(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

func (b *PaymentUpdate) defaults() error {

	return nil
}

func (b *PaymentUpdate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.patch.CardID.IsNull() {
		return &ValidationError{Name: "card_id", err: errors.New(`ent: field "Payment.card_id" is not nullable`)}
	}

	if b.mutation.patch.Amount.IsNull() {
		return &ValidationError{Name: "amount", err: errors.New(`ent: field "Payment.amount" is not nullable`)}
	}

	if v, ok := b.mutation.patch.Amount.Get(); ok && b.mutation.patch.expressions[payment.FieldAmount] == nil {

		if err := payment.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Payment.amount": %w`, err)}
		}

	}

	if b.mutation.patch.Currency.IsNull() {
		return &ValidationError{Name: "currency", err: errors.New(`ent: field "Payment.currency" is not nullable`)}
	}

	if v, ok := b.mutation.patch.Currency.Get(); ok && b.mutation.patch.expressions[payment.FieldCurrency] == nil {

		if err := payment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Payment.currency": %w`, err)}
		}

	}

	if b.mutation.patch.Time.IsNull() {
		return &ValidationError{Name: "time", err: errors.New(`ent: field "Payment.time" is not nullable`)}
	}

	if b.mutation.patch.Description.IsNull() {
		return &ValidationError{Name: "description", err: errors.New(`ent: field "Payment.description" is not nullable`)}
	}

	if b.mutation.patch.Status.IsNull() {
		return &ValidationError{Name: "status", err: errors.New(`ent: field "Payment.status" is not nullable`)}
	}

	if v, ok := b.mutation.patch.Status.Get(); ok && b.mutation.patch.expressions[payment.FieldStatus] == nil {

		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}

	}

	if b.mutation.patch.CardID.IsNull() {
		return &ValidationError{Name: "card", err: errors.New(`ent: clearing required edge "Payment.card"`)}
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PaymentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PaymentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PaymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.Amount.Get(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.patch.AmountAdd.Get(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.patch.Currency.Get(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.patch.Time.Get(); ok {
		_spec.SetField(payment.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.patch.Description.Get(); ok {
		_spec.SetField(payment.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.patch.Status.Get(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.patch.CardID.IsNull() || _u.mutation.patch.clearedEdges[payment.EdgeCard] {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.CardTable,
			Columns: []string{payment.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.cardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.CardTable,
			Columns: []string{payment.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Returning = _u.returning
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return _node, nil
}

type PaymentUpdateOne struct {
	config
	mutation *PaymentMutation
	err      error

	fields []string
	old    *Payment

	modifiers []func(*sql.UpdateBuilder)
}

func (b *PaymentUpdateOne) Set[T any](column ent.ColumnOf[entity.Payment, T], value T) *PaymentUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *PaymentUpdateOne) SetOptional[T any](column ent.ColumnOf[entity.Payment, T], value ent.Option[T]) *PaymentUpdateOne {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *PaymentUpdateOne) SetExpr[T any](column ent.ColumnOf[entity.Payment, T], value ent.Expr[T]) *PaymentUpdateOne {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case payment.FieldCardID:

	case payment.FieldAmount:

	case payment.FieldCurrency:

	case payment.FieldTime:

	case payment.FieldDescription:

	case payment.FieldStatus:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of Payment is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *PaymentUpdateOne) SetEdge[N, K any](edge ent.UniqueRelation[entity.Payment, N, K], id K) *PaymentUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *PaymentUpdateOne) AddIDs[N, K any](edge ent.Relation[entity.Payment, N, K], ids ...K) *PaymentUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *PaymentUpdateOne) Mutation() *PaymentMutation { return b.mutation }

func (b *PaymentUpdateOne) Patch() *PaymentPatch { return b.mutation.patch }
func (b *PaymentUpdateOne) Apply(p PaymentPatch) *PaymentUpdateOne {
	b.mutation.patch.apply(p)
	return b
}
func (b *PaymentUpdateOne) Add[T ent.Number](column ent.ColumnOf[entity.Payment, T], delta T) *PaymentUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *PaymentUpdateOne) Append[T any](column ent.ColumnOf[entity.Payment, T], values T) *PaymentUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *PaymentUpdateOne) Clear[T any](column ent.ColumnOf[entity.Payment, T]) *PaymentUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *PaymentUpdateOne) RemoveIDs[N, K any](edge ent.Relation[entity.Payment, N, K], ids ...K) *PaymentUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *PaymentUpdateOne) ClearEdge[N, K any](edge ent.RelationOf[entity.Payment, N, K]) *PaymentUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *PaymentUpdateOne) Where(predicates ...ent.Predicate[entity.Payment]) *PaymentUpdateOne {
	b.mutation.Where(predicates...)
	return b
}

func (b *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *PaymentUpdateOne) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *PaymentUpdateOne) Select(columns ...ent.EntityColumn[entity.Payment]) *PaymentUpdateOne {
	if len(columns) == 0 {
		panic("ent: Select requires at least one column")
	}
	b.fields = make([]string, len(columns))
	for index, column := range columns {
		b.fields[index] = column.Ref().Name
	}
	return b
}

func (b *PaymentUpdateOne) SaveOld(ctx context.Context) (old *Payment, updated *Payment, err error) {
	if !b.driver.Capabilities().ReturningOld {
		return nil, nil, &dialect.UnsupportedError{Feature: "RETURNING OLD", Dialect: dialect.Dialect(b.driver.Dialect())}
	}
	b.old = &Payment{config: b.config}
	defer func() { b.old = nil }()
	updated, err = b.Save(ctx)
	if err != nil {
		return nil, nil, err
	}
	return b.old, updated, nil
}

func (b *PaymentUpdateOne) defaults() error {

	return nil
}

func (b *PaymentUpdateOne) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.patch.CardID.IsNull() {
		return &ValidationError{Name: "card_id", err: errors.New(`ent: field "Payment.card_id" is not nullable`)}
	}

	if b.mutation.patch.Amount.IsNull() {
		return &ValidationError{Name: "amount", err: errors.New(`ent: field "Payment.amount" is not nullable`)}
	}

	if v, ok := b.mutation.patch.Amount.Get(); ok && b.mutation.patch.expressions[payment.FieldAmount] == nil {

		if err := payment.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Payment.amount": %w`, err)}
		}

	}

	if b.mutation.patch.Currency.IsNull() {
		return &ValidationError{Name: "currency", err: errors.New(`ent: field "Payment.currency" is not nullable`)}
	}

	if v, ok := b.mutation.patch.Currency.Get(); ok && b.mutation.patch.expressions[payment.FieldCurrency] == nil {

		if err := payment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Payment.currency": %w`, err)}
		}

	}

	if b.mutation.patch.Time.IsNull() {
		return &ValidationError{Name: "time", err: errors.New(`ent: field "Payment.time" is not nullable`)}
	}

	if b.mutation.patch.Description.IsNull() {
		return &ValidationError{Name: "description", err: errors.New(`ent: field "Payment.description" is not nullable`)}
	}

	if b.mutation.patch.Status.IsNull() {
		return &ValidationError{Name: "status", err: errors.New(`ent: field "Payment.status" is not nullable`)}
	}

	if v, ok := b.mutation.patch.Status.Get(); ok && b.mutation.patch.expressions[payment.FieldStatus] == nil {

		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}

	}

	if b.mutation.patch.CardID.IsNull() {
		return &ValidationError{Name: "card", err: errors.New(`ent: clearing required edge "Payment.card"`)}
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PaymentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PaymentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.Amount.Get(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.patch.AmountAdd.Get(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.patch.Currency.Get(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.patch.Time.Get(); ok {
		_spec.SetField(payment.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.patch.Description.Get(); ok {
		_spec.SetField(payment.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.patch.Status.Get(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.patch.CardID.IsNull() || _u.mutation.patch.clearedEdges[payment.EdgeCard] {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.CardTable,
			Columns: []string{payment.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.cardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.CardTable,
			Columns: []string{payment.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	_node = &Payment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if _u.old != nil {
		_spec.OldScanValues = _u.old.scanValues
		_spec.OldAssign = _u.old.assignValues
	}
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
