// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/examples/o2orecur/ent/entity"
	"github.com/neko-sc/ent/examples/o2orecur/ent/node"
)

// Node is the model entity for the Node schema.
type Node struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Value holds the value of the "value" field.
	Value int `json:"value,omitempty"`
	// PrevID holds the value of the "prev_id" field.
	PrevID int `json:"prev_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NodeQuery when eager-loading is set.
	Edges NodeEdges `json:"edges"`
}

// NodeEdges holds the relations/edges for other nodes in the graph.
type NodeEdges struct {
	// Prev holds the value of the prev edge.
	Prev *Node `json:"prev,omitempty"`
	// Next holds the value of the next edge.
	Next *Node `json:"next,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	counts      map[string]int
}

func (e NodeEdges) Loaded[N, K any](edge ent.RelationOf[entity.Node, N, K]) bool {
	switch edge.Ref().Name {
	case "prev":
		return e.loadedTypes[0]
	case "next":
		return e.loadedTypes[1]

	default:
		return false
	}
}

func (e *NodeEdges) SetLoaded[N, K any](edge ent.RelationOf[entity.Node, N, K], loaded bool) {
	switch edge.Ref().Name {
	case "prev":
		e.loadedTypes[0] = loaded
	case "next":
		e.loadedTypes[1] = loaded

	}
}

func (e NodeEdges) Count[N, K any](edge ent.Relation[entity.Node, N, K]) (int, bool) {
	count, loaded := e.counts[edge.Ref().Name]
	return count, loaded
}

// PrevOrErr returns the Prev value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeEdges) PrevOrErr() (*Node, error) {
	if e.Prev != nil {
		return e.Prev, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "prev"}
}

// NextOrErr returns the Next value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeEdges) NextOrErr() (*Node, error) {
	if e.Next != nil {
		return e.Next, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "next"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Node) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case node.FieldID, node.FieldValue, node.FieldPrevID:
			values[i] = new(*int)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Node fields.
func (_m *Node) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case node.FieldID:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil && *value != nil {
				_m.ID = **value
			}
		case node.FieldValue:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value != nil && *value != nil {
				_m.Value = **value
			}
		case node.FieldPrevID:

			if value, ok := values[i].(**int); !ok {
				return fmt.Errorf("unexpected type %T for field prev_id", values[i])
			} else if value != nil && *value != nil {
				_m.PrevID = **value
			}
		}
	}
	return nil
}

// QueryPrev queries the "prev" edge of the Node entity.
func (_m *Node) QueryPrev() *NodeQuery {
	return NewNodeClient(_m.config).QueryPrev(_m)
}

// QueryNext queries the "next" edge of the Node entity.
func (_m *Node) QueryNext() *NodeQuery {
	return NewNodeClient(_m.config).QueryNext(_m)
}

// Update returns a builder for updating this Node.
// Note that you need to call Node.Unwrap() before calling this method if this Node
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Node) Update() *NodeUpdateOne {
	return NewNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Node entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Node) Unwrap() *Node {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Node is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Node) String() string {
	var builder strings.Builder
	builder.WriteString("Node(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value))
	builder.WriteString(", ")
	builder.WriteString("prev_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrevID))
	builder.WriteByte(')')
	return builder.String()
}

// Nodes is a parsable slice of Node.
type Nodes []*Node
