// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect"
	"github.com/neko-sc/ent/dialect/sql"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/examples/edgeindex/ent/city"
	"github.com/neko-sc/ent/examples/edgeindex/ent/entity"
	"github.com/neko-sc/ent/examples/edgeindex/ent/street"
	"github.com/neko-sc/ent/schema/field"
)

type CityUpdate struct {
	config
	mutation  *CityMutation
	err       error
	returning *sqlgraph.Returning

	modifiers []func(*sql.UpdateBuilder)
}

func (b *CityUpdate) Set[T any](column ent.ColumnOf[entity.City, T], value T) *CityUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *CityUpdate) SetOptional[T any](column ent.ColumnOf[entity.City, T], value ent.Option[T]) *CityUpdate {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *CityUpdate) SetExpr[T any](column ent.ColumnOf[entity.City, T], value ent.Expr[T]) *CityUpdate {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case city.FieldName:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of City is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *CityUpdate) SetEdge[N, K any](edge ent.UniqueRelation[entity.City, N, K], id K) *CityUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *CityUpdate) AddIDs[N, K any](edge ent.Relation[entity.City, N, K], ids ...K) *CityUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CityUpdate) Mutation() *CityMutation { return b.mutation }

func (b *CityUpdate) Patch() *CityPatch             { return b.mutation.patch }
func (b *CityUpdate) Apply(p CityPatch) *CityUpdate { b.mutation.patch.apply(p); return b }
func (b *CityUpdate) Add[T ent.Number](column ent.ColumnOf[entity.City, T], delta T) *CityUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *CityUpdate) Append[T any](column ent.ColumnOf[entity.City, T], values T) *CityUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *CityUpdate) Clear[T any](column ent.ColumnOf[entity.City, T]) *CityUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *CityUpdate) RemoveIDs[N, K any](edge ent.Relation[entity.City, N, K], ids ...K) *CityUpdate {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CityUpdate) ClearEdge[N, K any](edge ent.RelationOf[entity.City, N, K]) *CityUpdate {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *CityUpdate) Where(predicates ...ent.Predicate[entity.City]) *CityUpdate {
	b.mutation.Where(predicates...)
	return b
}

func (b *CityUpdate) Save(ctx context.Context) (int, error) {
	if b.err != nil {
		return 0, b.err
	}
	if err := b.defaults(); err != nil {
		return 0, err
	}
	return b.sqlSave(ctx)
}

func (b *CityUpdate) SaveX(ctx context.Context) int {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *CityUpdate) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CityUpdate) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *CityUpdate) Returning(ctx context.Context) ([]*City, error) {
	nodes := make([]*City, 0)
	b.returning = &sqlgraph.Returning{Columns: city.Columns, Scan: func(rows dialect.Rows) error {
		_node := &City{config: b.config}
		values, err := _node.scanValues(city.Columns)
		if err != nil {
			return err
		}
		if err := rows.Scan(values...); err != nil {
			return err
		}
		if err := _node.assignValues(city.Columns, values); err != nil {
			return err
		}
		nodes = append(nodes, _node)
		return nil
	}}
	defer func() { b.returning = nil }()
	if _, err := b.Save(ctx); err != nil {
		return nil, err
	}
	return nodes, nil
}

func (b *CityUpdate) defaults() error {

	return nil
}

func (b *CityUpdate) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.patch.Name.IsNull() {
		return &ValidationError{Name: "name", err: errors.New(`ent: field "City.name" is not nullable`)}
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CityUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CityUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(city.Table, city.Columns, sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.Name.Get(); ok {
		_spec.SetField(city.FieldName, field.TypeString, value)
	}
	if _u.mutation.patch.Streets.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.StreetsTable,
			Columns: []string{city.StreetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(street.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Streets.Remove; len(nodes) > 0 && !_u.mutation.patch.Streets.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.StreetsTable,
			Columns: []string{city.StreetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(street.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.streetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.StreetsTable,
			Columns: []string{city.StreetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(street.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Returning = _u.returning
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{city.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return _node, nil
}

type CityUpdateOne struct {
	config
	mutation *CityMutation
	err      error

	fields []string
	old    *City

	modifiers []func(*sql.UpdateBuilder)
}

func (b *CityUpdateOne) Set[T any](column ent.ColumnOf[entity.City, T], value T) *CityUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.set(column.Ref().Name, value)
	}

	return b
}
func (b *CityUpdateOne) SetOptional[T any](column ent.ColumnOf[entity.City, T], value ent.Option[T]) *CityUpdateOne {
	if value.IsNull() {
		if b.err == nil {
			b.err = b.mutation.patch.setNull(column.Ref().Name)
		}
		return b
	}
	if value, ok := value.Get(); ok {
		return b.Set(column, value)
	}
	return b
}
func (b *CityUpdateOne) SetExpr[T any](column ent.ColumnOf[entity.City, T], value ent.Expr[T]) *CityUpdateOne {
	if b.err != nil {
		return b
	}
	switch column.Ref().Name {

	case city.FieldName:

	default:
		b.err = &ValidationError{Name: column.Ref().Name, err: fmt.Errorf("ent: field %q of City is not settable", column.Ref().Name)}
		return b
	}

	b.mutation.patch.setExpr(column.Ref().Name, value.Render)

	return b

}
func (b *CityUpdateOne) SetEdge[N, K any](edge ent.UniqueRelation[entity.City, N, K], id K) *CityUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setEdge(edge.Ref().Name, id)
	}

	return b
}
func (b *CityUpdateOne) AddIDs[N, K any](edge ent.Relation[entity.City, N, K], ids ...K) *CityUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.addIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CityUpdateOne) Mutation() *CityMutation { return b.mutation }

func (b *CityUpdateOne) Patch() *CityPatch                { return b.mutation.patch }
func (b *CityUpdateOne) Apply(p CityPatch) *CityUpdateOne { b.mutation.patch.apply(p); return b }
func (b *CityUpdateOne) Add[T ent.Number](column ent.ColumnOf[entity.City, T], delta T) *CityUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.add(column.Ref().Name, delta)
	}
	return b
}
func (b *CityUpdateOne) Append[T any](column ent.ColumnOf[entity.City, T], values T) *CityUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.appendValues(column.Ref().Name, values)
	}
	return b
}
func (b *CityUpdateOne) Clear[T any](column ent.ColumnOf[entity.City, T]) *CityUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.setNull(column.Ref().Name)
	}
	return b
}
func (b *CityUpdateOne) RemoveIDs[N, K any](edge ent.Relation[entity.City, N, K], ids ...K) *CityUpdateOne {
	values := make([]any, len(ids))
	for index := range ids {
		values[index] = ids[index]
	}
	if b.err == nil {
		b.err = b.mutation.patch.removeIDs(edge.Ref().Name, values...)
	}
	return b
}
func (b *CityUpdateOne) ClearEdge[N, K any](edge ent.RelationOf[entity.City, N, K]) *CityUpdateOne {
	if b.err == nil {
		b.err = b.mutation.patch.clearEdge(edge.Ref().Name)
	}
	return b
}

func (b *CityUpdateOne) Where(predicates ...ent.Predicate[entity.City]) *CityUpdateOne {
	b.mutation.Where(predicates...)
	return b
}

func (b *CityUpdateOne) Save(ctx context.Context) (*City, error) {
	if b.err != nil {
		return nil, b.err
	}
	if err := b.defaults(); err != nil {
		return nil, err
	}
	return b.sqlSave(ctx)
}

func (b *CityUpdateOne) SaveX(ctx context.Context) *City {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

func (b *CityUpdateOne) Exec(ctx context.Context) error { _, err := b.Save(ctx); return err }

func (b *CityUpdateOne) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

func (b *CityUpdateOne) Select(columns ...ent.EntityColumn[entity.City]) *CityUpdateOne {
	if len(columns) == 0 {
		panic("ent: Select requires at least one column")
	}
	b.fields = make([]string, len(columns))
	for index, column := range columns {
		b.fields[index] = column.Ref().Name
	}
	return b
}

func (b *CityUpdateOne) SaveOld(ctx context.Context) (old *City, updated *City, err error) {
	if !b.driver.Capabilities().ReturningOld {
		return nil, nil, &dialect.UnsupportedError{Feature: "RETURNING OLD", Dialect: dialect.Dialect(b.driver.Dialect())}
	}
	b.old = &City{config: b.config}
	defer func() { b.old = nil }()
	updated, err = b.Save(ctx)
	if err != nil {
		return nil, nil, err
	}
	return b.old, updated, nil
}

func (b *CityUpdateOne) defaults() error {

	return nil
}

func (b *CityUpdateOne) check() error {
	if b.err != nil {
		return b.err
	}

	if b.mutation.patch.Name.IsNull() {
		return &ValidationError{Name: "name", err: errors.New(`ent: field "City.name" is not nullable`)}
	}

	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CityUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CityUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CityUpdateOne) sqlSave(ctx context.Context) (_node *City, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(city.Table, city.Columns, sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "City.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, city.FieldID)
		for _, f := range fields {
			if !city.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != city.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.patch.Name.Get(); ok {
		_spec.SetField(city.FieldName, field.TypeString, value)
	}
	if _u.mutation.patch.Streets.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.StreetsTable,
			Columns: []string{city.StreetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(street.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.Streets.Remove; len(nodes) > 0 && !_u.mutation.patch.Streets.Clear {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.StreetsTable,
			Columns: []string{city.StreetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(street.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.patch.streetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.StreetsTable,
			Columns: []string{city.StreetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(street.FieldID, field.TypeInt),
			},
		}
		seen := make(map[int]struct{}, len(nodes))
		for _, k := range nodes {
			if _, exists := seen[k]; exists {
				continue
			}
			seen[k] = struct{}{}
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	for column, render := range _u.mutation.patch.expressions {
		_spec.AddModifier(func(update *sql.UpdateBuilder) { update.Set(column, sql.ExprFunc(render)) })
	}
	_spec.AddModifiers(_u.modifiers...)

	_node = &City{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if _u.old != nil {
		_spec.OldScanValues = _u.old.scanValues
		_spec.OldAssign = _u.old.assignValues
	}
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{city.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
