// Copyright 2019-2026 Facebook Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ent, DO NOT EDIT.

package metadata

import (
	"github.com/neko-sc/ent"
	"github.com/neko-sc/ent/dialect/sql/sqlgraph"
	"github.com/neko-sc/ent/entc/integration/edgefield/ent/entity"
)

const (
	// Label holds the string label denoting the metadata type in the database.
	Label = "metadata"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// Table holds the table name of the metadata in the database.
	Table = "metadata"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "metadata"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "id"
	// ChildrenTable is the table that holds the children relation/edge.
	ChildrenTable = "metadata"
	// ChildrenColumn is the table column denoting the children relation/edge.
	ChildrenColumn = "parent_id"
	// ParentTable is the table that holds the parent relation/edge.
	ParentTable = "metadata"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "parent_id"
)

var (
	ID       = ent.OrderedColumn[entity.Metadata, int]{Table: Table, Name: FieldID}
	Age      = ent.OrderedColumn[entity.Metadata, int]{Table: Table, Name: FieldAge}
	ParentID = ent.OrderedColumn[entity.Metadata, int]{Table: Table, Name: FieldParentID}
	User     = ent.NewUniqueRelation[entity.Metadata, entity.User, int](EdgeUser, newUserStep)
	Children = ent.NewRelation[entity.Metadata, entity.Metadata, int](EdgeChildren, newChildrenStep)
	Parent   = ent.NewUniqueRelation[entity.Metadata, entity.Metadata, int](EdgeParent, newParentStep)
)

// Alias returns the columns of the metadata table under a different table alias.
func Alias(name string) AliasedTable {
	return AliasedTable{
		TableAlias: name,
		ID:         ent.OrderedColumn[entity.Metadata, int]{Table: name, Name: FieldID},
		Age:        ent.OrderedColumn[entity.Metadata, int]{Table: name, Name: FieldAge},
		ParentID:   ent.OrderedColumn[entity.Metadata, int]{Table: name, Name: FieldParentID},
	}
}

// AliasedTable holds typed columns qualified by TableAlias.
type AliasedTable struct {
	TableAlias string
	ID         ent.OrderedColumn[entity.Metadata, int]
	Age        ent.OrderedColumn[entity.Metadata, int]
	ParentID   ent.OrderedColumn[entity.Metadata, int]
}

// And joins predicates with AND.
func And(predicates ...ent.Predicate[entity.Metadata]) ent.Predicate[entity.Metadata] {
	return ent.And(predicates...)
}

// Or joins predicates with OR.
func Or(predicates ...ent.Predicate[entity.Metadata]) ent.Predicate[entity.Metadata] {
	return ent.Or(predicates...)
}

// Not negates a predicate.
func Not(predicate ent.Predicate[entity.Metadata]) ent.Predicate[entity.Metadata] {
	return ent.Not(predicate)
}

// Columns holds all SQL columns for metadata fields.
var Columns = []string{
	FieldID,
	FieldAge,
	FieldParentID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAge holds the default value on creation for the "age" field.
	DefaultAge int
)

func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
func newChildrenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ChildrenTable, ChildrenColumn),
	)
}
func newParentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ParentTable, ParentColumn),
	)
}
